namespace Bia.Countries.Iso3166
{
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public static partial class Countries
    {
        public static readonly ReadOnlyCollection<Country> CountryList = new List<Country>()
        {
            new Country(
                shortName: "Afghanistan",
                fullName: "the Islamic Republic of Afghanistan",
                activeDirectoryName: "Afghanistan",
                alpha2: CountryCode.AF,
                alpha3: CountryCodeAlpha3.AFG,
                numeric: 4),
            new Country(
                shortName: "Åland Islands",
                fullName: null,
                activeDirectoryName: "Åland Islands",
                alpha2: CountryCode.AX,
                alpha3: CountryCodeAlpha3.ALA,
                numeric: 248),
            new Country(
                shortName: "Albania",
                fullName: "the Republic of Albania",
                activeDirectoryName: "Albania",
                alpha2: CountryCode.AL,
                alpha3: CountryCodeAlpha3.ALB,
                numeric: 8),
            new Country(
                shortName: "Algeria",
                fullName: "the People's Democratic Republic of Algeria",
                activeDirectoryName: "Algeria",
                alpha2: CountryCode.DZ,
                alpha3: CountryCodeAlpha3.DZA,
                numeric: 12),
            new Country(
                shortName: "American Samoa",
                fullName: null,
                activeDirectoryName: "American Samoa",
                alpha2: CountryCode.AS,
                alpha3: CountryCodeAlpha3.ASM,
                numeric: 16),
            new Country(
                shortName: "Andorra",
                fullName: "the Principality of Andorra",
                activeDirectoryName: "Andorra",
                alpha2: CountryCode.AD,
                alpha3: CountryCodeAlpha3.AND,
                numeric: 20),
            new Country(
                shortName: "Angola",
                fullName: "the Republic of Angola",
                activeDirectoryName: "Angola",
                alpha2: CountryCode.AO,
                alpha3: CountryCodeAlpha3.AGO,
                numeric: 24),
            new Country(
                shortName: "Anguilla",
                fullName: null,
                activeDirectoryName: "Anguilla",
                alpha2: CountryCode.AI,
                alpha3: CountryCodeAlpha3.AIA,
                numeric: 660),
            new Country(
                shortName: "Antarctica",
                fullName: null,
                activeDirectoryName: "Antarctica",
                alpha2: CountryCode.AQ,
                alpha3: CountryCodeAlpha3.ATA,
                numeric: 10),
            new Country(
                shortName: "Antigua and Barbuda",
                fullName: null,
                activeDirectoryName: "Antigua and Barbuda",
                alpha2: CountryCode.AG,
                alpha3: CountryCodeAlpha3.ATG,
                numeric: 28),
            new Country(
                shortName: "Argentina",
                fullName: "the Argentine Republic",
                activeDirectoryName: "Argentina",
                alpha2: CountryCode.AR,
                alpha3: CountryCodeAlpha3.ARG,
                numeric: 32),
            new Country(
                shortName: "Armenia",
                fullName: "the Republic of Armenia",
                activeDirectoryName: "Armenia",
                alpha2: CountryCode.AM,
                alpha3: CountryCodeAlpha3.ARM,
                numeric: 51),
            new Country(
                shortName: "Aruba",
                fullName: null,
                activeDirectoryName: "Aruba",
                alpha2: CountryCode.AW,
                alpha3: CountryCodeAlpha3.ABW,
                numeric: 533),
            new Country(
                shortName: "Australia",
                fullName: null,
                activeDirectoryName: "Australia",
                alpha2: CountryCode.AU,
                alpha3: CountryCodeAlpha3.AUS,
                numeric: 36),
            new Country(
                shortName: "Austria",
                fullName: "the Republic of Austria",
                activeDirectoryName: "Austria",
                alpha2: CountryCode.AT,
                alpha3: CountryCodeAlpha3.AUT,
                numeric: 40),
            new Country(
                shortName: "Azerbaijan",
                fullName: "the Republic of Azerbaijan",
                activeDirectoryName: "Azerbaijan",
                alpha2: CountryCode.AZ,
                alpha3: CountryCodeAlpha3.AZE,
                numeric: 31),
            new Country(
                shortName: "Bahamas",
                fullName: "the Commonwealth of the Bahamas",
                activeDirectoryName: "Bahamas, The",
                alpha2: CountryCode.BS,
                alpha3: CountryCodeAlpha3.BHS,
                numeric: 44),
            new Country(
                shortName: "Bahrain",
                fullName: "the Kingdom of Bahrain",
                activeDirectoryName: "Bahrain",
                alpha2: CountryCode.BH,
                alpha3: CountryCodeAlpha3.BHR,
                numeric: 48),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Baker Island",
                alpha2: CountryCode.None,
                alpha3: CountryCodeAlpha3.None,
                numeric: 581),
            new Country(
                shortName: "Bangladesh",
                fullName: "the People's Republic of Bangladesh",
                activeDirectoryName: "Bangladesh",
                alpha2: CountryCode.BD,
                alpha3: CountryCodeAlpha3.BGD,
                numeric: 50),
            new Country(
                shortName: "Barbados",
                fullName: null,
                activeDirectoryName: "Barbados",
                alpha2: CountryCode.BB,
                alpha3: CountryCodeAlpha3.BRB,
                numeric: 52),
            new Country(
                shortName: "Belarus",
                fullName: "the Republic of Belarus",
                activeDirectoryName: "Belarus",
                alpha2: CountryCode.BY,
                alpha3: CountryCodeAlpha3.BLR,
                numeric: 112),
            new Country(
                shortName: "Belgium",
                fullName: "the Kingdom of Belgium",
                activeDirectoryName: "Belgium",
                alpha2: CountryCode.BE,
                alpha3: CountryCodeAlpha3.BEL,
                numeric: 56),
            new Country(
                shortName: "Belize",
                fullName: null,
                activeDirectoryName: "Belize",
                alpha2: CountryCode.BZ,
                alpha3: CountryCodeAlpha3.BLZ,
                numeric: 84),
            new Country(
                shortName: "Benin",
                fullName: "the Republic of Benin",
                activeDirectoryName: "Benin",
                alpha2: CountryCode.BJ,
                alpha3: CountryCodeAlpha3.BEN,
                numeric: 204),
            new Country(
                shortName: "Bermuda",
                fullName: null,
                activeDirectoryName: "Bermuda",
                alpha2: CountryCode.BM,
                alpha3: CountryCodeAlpha3.BMU,
                numeric: 60),
            new Country(
                shortName: "Bhutan",
                fullName: "the Kingdom of Bhutan",
                activeDirectoryName: "Bhutan",
                alpha2: CountryCode.BT,
                alpha3: CountryCodeAlpha3.BTN,
                numeric: 64),
            new Country(
                shortName: "Bolivia (Plurinational State of)",
                fullName: "the Plurinational State of Bolivia",
                activeDirectoryName: "Bolivia",
                alpha2: CountryCode.BO,
                alpha3: CountryCodeAlpha3.BOL,
                numeric: 68),
            new Country(
                shortName: "Bonaire, Sint Eustatius and Saba",
                fullName: null,
                activeDirectoryName: "Bonaire, Sint Eustatius and Saba",
                alpha2: CountryCode.BQ,
                alpha3: CountryCodeAlpha3.BES,
                numeric: 535),
            new Country(
                shortName: "Bosnia and Herzegovina",
                fullName: null,
                activeDirectoryName: "Bosnia and Herzegovina",
                alpha2: CountryCode.BA,
                alpha3: CountryCodeAlpha3.BIH,
                numeric: 70),
            new Country(
                shortName: "Botswana",
                fullName: "the Republic of Botswana",
                activeDirectoryName: "Botswana",
                alpha2: CountryCode.BW,
                alpha3: CountryCodeAlpha3.BWA,
                numeric: 72),
            new Country(
                shortName: "Bouvet Island",
                fullName: null,
                activeDirectoryName: "Bouvet Island",
                alpha2: CountryCode.BV,
                alpha3: CountryCodeAlpha3.BVT,
                numeric: 74),
            new Country(
                shortName: "Brazil",
                fullName: "the Federative Republic of Brazil",
                activeDirectoryName: "Brazil",
                alpha2: CountryCode.BR,
                alpha3: CountryCodeAlpha3.BRA,
                numeric: 76),
            new Country(
                shortName: "British Indian Ocean Territory",
                fullName: "the British Indian Ocean Territory",
                activeDirectoryName: "British Indian Ocean Territory",
                alpha2: CountryCode.IO,
                alpha3: CountryCodeAlpha3.IOT,
                numeric: 86),
            new Country(
                shortName: "Brunei Darussalam",
                fullName: null,
                activeDirectoryName: "Brunei",
                alpha2: CountryCode.BN,
                alpha3: CountryCodeAlpha3.BRN,
                numeric: 96),
            new Country(
                shortName: "Bulgaria",
                fullName: "the Republic of Bulgaria",
                activeDirectoryName: "Bulgaria",
                alpha2: CountryCode.BG,
                alpha3: CountryCodeAlpha3.BGR,
                numeric: 100),
            new Country(
                shortName: "Burkina Faso",
                fullName: null,
                activeDirectoryName: "Burkina Faso",
                alpha2: CountryCode.BF,
                alpha3: CountryCodeAlpha3.BFA,
                numeric: 854),
            new Country(
                shortName: "Burundi",
                fullName: "the Republic of Burundi",
                activeDirectoryName: "Burundi",
                alpha2: CountryCode.BI,
                alpha3: CountryCodeAlpha3.BDI,
                numeric: 108),
            new Country(
                shortName: "Cabo Verde",
                fullName: "the Republic of Cabo Verde",
                activeDirectoryName: "Cape Verde",
                alpha2: CountryCode.CV,
                alpha3: CountryCodeAlpha3.CPV,
                numeric: 132),
            new Country(
                shortName: "Cambodia",
                fullName: "the Kingdom of Cambodia",
                activeDirectoryName: "Cambodia",
                alpha2: CountryCode.KH,
                alpha3: CountryCodeAlpha3.KHM,
                numeric: 116),
            new Country(
                shortName: "Cameroon",
                fullName: "the Republic of Cameroon",
                activeDirectoryName: "Cameroon",
                alpha2: CountryCode.CM,
                alpha3: CountryCodeAlpha3.CMR,
                numeric: 120),
            new Country(
                shortName: "Canada",
                fullName: null,
                activeDirectoryName: "Canada",
                alpha2: CountryCode.CA,
                alpha3: CountryCodeAlpha3.CAN,
                numeric: 124),
            new Country(
                shortName: "Cayman Islands",
                fullName: "the Cayman Islands",
                activeDirectoryName: "Cayman Islands",
                alpha2: CountryCode.KY,
                alpha3: CountryCodeAlpha3.CYM,
                numeric: 136),
            new Country(
                shortName: "Central African Republic",
                fullName: "the Central African Republic",
                activeDirectoryName: "Central African Republic",
                alpha2: CountryCode.CF,
                alpha3: CountryCodeAlpha3.CAF,
                numeric: 140),
            new Country(
                shortName: "Chad",
                fullName: "the Republic of Chad",
                activeDirectoryName: "Chad",
                alpha2: CountryCode.TD,
                alpha3: CountryCodeAlpha3.TCD,
                numeric: 148),
            new Country(
                shortName: "Chile",
                fullName: "the Republic of Chile",
                activeDirectoryName: "Chile",
                alpha2: CountryCode.CL,
                alpha3: CountryCodeAlpha3.CHL,
                numeric: 152),
            new Country(
                shortName: "China",
                fullName: "the People's Republic of China",
                activeDirectoryName: "China",
                alpha2: CountryCode.CN,
                alpha3: CountryCodeAlpha3.CHN,
                numeric: 156),
            new Country(
                shortName: "Christmas Island",
                fullName: null,
                activeDirectoryName: "Christmas Island",
                alpha2: CountryCode.CX,
                alpha3: CountryCodeAlpha3.CXR,
                numeric: 162),
            new Country(
                shortName: "Cocos (Keeling) Islands",
                fullName: "the Cocos (Keeling) Islands",
                activeDirectoryName: "Cocos (Keeling) Islands",
                alpha2: CountryCode.CC,
                alpha3: CountryCodeAlpha3.CCK,
                numeric: 166),
            new Country(
                shortName: "Colombia",
                fullName: "the Republic of Colombia",
                activeDirectoryName: "Colombia",
                alpha2: CountryCode.CO,
                alpha3: CountryCodeAlpha3.COL,
                numeric: 170),
            new Country(
                shortName: "Comoros",
                fullName: "the Union of the Comoros",
                activeDirectoryName: "Comoros",
                alpha2: CountryCode.KM,
                alpha3: CountryCodeAlpha3.COM,
                numeric: 174),
            new Country(
                shortName: "Congo, Democratic Republic of the",
                fullName: "the Democratic Republic of the Congo",
                activeDirectoryName: "Congo (DRC)",
                alpha2: CountryCode.CD,
                alpha3: CountryCodeAlpha3.COD,
                numeric: 180),
            new Country(
                shortName: "Congo",
                fullName: "the Republic of the Congo",
                activeDirectoryName: "Congo",
                alpha2: CountryCode.CG,
                alpha3: CountryCodeAlpha3.COG,
                numeric: 178),
            new Country(
                shortName: "Cook Islands",
                fullName: null,
                activeDirectoryName: "Cook Islands",
                alpha2: CountryCode.CK,
                alpha3: CountryCodeAlpha3.COK,
                numeric: 184),
            new Country(
                shortName: "Costa Rica",
                fullName: "the Republic of Costa Rica",
                activeDirectoryName: "Costa Rica",
                alpha2: CountryCode.CR,
                alpha3: CountryCodeAlpha3.CRI,
                numeric: 188),
            new Country(
                shortName: "Côte d'Ivoire",
                fullName: "the Republic of Côte d'Ivoire",
                activeDirectoryName: "Côte d'Ivoire",
                alpha2: CountryCode.CI,
                alpha3: CountryCodeAlpha3.CIV,
                numeric: 384),
            new Country(
                shortName: "Croatia",
                fullName: "the Republic of Croatia",
                activeDirectoryName: "Croatia",
                alpha2: CountryCode.HR,
                alpha3: CountryCodeAlpha3.HRV,
                numeric: 191),
            new Country(
                shortName: "Cuba",
                fullName: "the Republic of Cuba",
                activeDirectoryName: "Cuba",
                alpha2: CountryCode.CU,
                alpha3: CountryCodeAlpha3.CUB,
                numeric: 192),
            new Country(
                shortName: "Curaçao",
                fullName: null,
                activeDirectoryName: "Curaçao",
                alpha2: CountryCode.CW,
                alpha3: CountryCodeAlpha3.CUW,
                numeric: 531),
            new Country(
                shortName: "Cyprus",
                fullName: "the Republic of Cyprus",
                activeDirectoryName: "Cyprus",
                alpha2: CountryCode.CY,
                alpha3: CountryCodeAlpha3.CYP,
                numeric: 196),
            new Country(
                shortName: "Czechia",
                fullName: "the Czech Republic",
                activeDirectoryName: "Czech Republic",
                alpha2: CountryCode.CZ,
                alpha3: CountryCodeAlpha3.CZE,
                numeric: 203),
            new Country(
                shortName: "Denmark",
                fullName: "the Kingdom of Denmark",
                activeDirectoryName: "Denmark",
                alpha2: CountryCode.DK,
                alpha3: CountryCodeAlpha3.DNK,
                numeric: 208),
            new Country(
                shortName: "Djibouti",
                fullName: "the Republic of Djibouti",
                activeDirectoryName: "Djibouti",
                alpha2: CountryCode.DJ,
                alpha3: CountryCodeAlpha3.DJI,
                numeric: 262),
            new Country(
                shortName: "Dominica",
                fullName: "the Commonwealth of Dominica",
                activeDirectoryName: "Dominica",
                alpha2: CountryCode.DM,
                alpha3: CountryCodeAlpha3.DMA,
                numeric: 212),
            new Country(
                shortName: "Dominican Republic",
                fullName: "the Dominican Republic",
                activeDirectoryName: "Dominican Republic",
                alpha2: CountryCode.DO,
                alpha3: CountryCodeAlpha3.DOM,
                numeric: 214),
            new Country(
                shortName: "Ecuador",
                fullName: "the Republic of Ecuador",
                activeDirectoryName: "Ecuador",
                alpha2: CountryCode.EC,
                alpha3: CountryCodeAlpha3.ECU,
                numeric: 218),
            new Country(
                shortName: "Egypt",
                fullName: "the Arab Republic of Egypt",
                activeDirectoryName: "Egypt",
                alpha2: CountryCode.EG,
                alpha3: CountryCodeAlpha3.EGY,
                numeric: 818),
            new Country(
                shortName: "El Salvador",
                fullName: "the Republic of El Salvador",
                activeDirectoryName: "El Salvador",
                alpha2: CountryCode.SV,
                alpha3: CountryCodeAlpha3.SLV,
                numeric: 222),
            new Country(
                shortName: "Equatorial Guinea",
                fullName: "the Republic of Equatorial Guinea",
                activeDirectoryName: "Equatorial Guinea",
                alpha2: CountryCode.GQ,
                alpha3: CountryCodeAlpha3.GNQ,
                numeric: 226),
            new Country(
                shortName: "Eritrea",
                fullName: "the State of Eritrea",
                activeDirectoryName: "Eritrea",
                alpha2: CountryCode.ER,
                alpha3: CountryCodeAlpha3.ERI,
                numeric: 232),
            new Country(
                shortName: "Estonia",
                fullName: "the Republic of Estonia",
                activeDirectoryName: "Estonia",
                alpha2: CountryCode.EE,
                alpha3: CountryCodeAlpha3.EST,
                numeric: 233),
            new Country(
                shortName: "Ethiopia",
                fullName: "the Federal Democratic Republic of Ethiopia",
                activeDirectoryName: "Ethiopia",
                alpha2: CountryCode.ET,
                alpha3: CountryCodeAlpha3.ETH,
                numeric: 231),
            new Country(
                shortName: "Falkland Islands (Malvinas)",
                fullName: null,
                activeDirectoryName: "Falkland Islands (Islas Malvinas)",
                alpha2: CountryCode.FK,
                alpha3: CountryCodeAlpha3.FLK,
                numeric: 238),
            new Country(
                shortName: "Faroe Islands",
                fullName: null,
                activeDirectoryName: "Faroe Islands",
                alpha2: CountryCode.FO,
                alpha3: CountryCodeAlpha3.FRO,
                numeric: 234),
            new Country(
                shortName: "Fiji",
                fullName: "the Republic of Fiji",
                activeDirectoryName: "Fiji Islands",
                alpha2: CountryCode.FJ,
                alpha3: CountryCodeAlpha3.FJI,
                numeric: 242),
            new Country(
                shortName: "Finland",
                fullName: "the Republic of Finland",
                activeDirectoryName: "Finland",
                alpha2: CountryCode.FI,
                alpha3: CountryCodeAlpha3.FIN,
                numeric: 246),
            new Country(
                shortName: "France",
                fullName: "the French Republic",
                activeDirectoryName: "France",
                alpha2: CountryCode.FR,
                alpha3: CountryCodeAlpha3.FRA,
                numeric: 250),
            new Country(
                shortName: "French Guiana",
                fullName: null,
                activeDirectoryName: "French Guiana",
                alpha2: CountryCode.GF,
                alpha3: CountryCodeAlpha3.GUF,
                numeric: 254),
            new Country(
                shortName: "French Polynesia",
                fullName: null,
                activeDirectoryName: "French Polynesia",
                alpha2: CountryCode.PF,
                alpha3: CountryCodeAlpha3.PYF,
                numeric: 258),
            new Country(
                shortName: "French Southern Territories",
                fullName: null,
                activeDirectoryName: "French Southern and Antarctic Lands",
                alpha2: CountryCode.TF,
                alpha3: CountryCodeAlpha3.ATF,
                numeric: 260),
            new Country(
                shortName: "Gabon",
                fullName: "the Gabonese Republic",
                activeDirectoryName: "Gabon",
                alpha2: CountryCode.GA,
                alpha3: CountryCodeAlpha3.GAB,
                numeric: 266),
            new Country(
                shortName: "Gambia",
                fullName: "the Islamic Republic of the Gambia",
                activeDirectoryName: "Gambia, The",
                alpha2: CountryCode.GM,
                alpha3: CountryCodeAlpha3.GMB,
                numeric: 270),
            new Country(
                shortName: "Georgia",
                fullName: null,
                activeDirectoryName: "Georgia",
                alpha2: CountryCode.GE,
                alpha3: CountryCodeAlpha3.GEO,
                numeric: 268),
            new Country(
                shortName: "Germany",
                fullName: "the Federal Republic of Germany",
                activeDirectoryName: "Germany",
                alpha2: CountryCode.DE,
                alpha3: CountryCodeAlpha3.DEU,
                numeric: 276),
            new Country(
                shortName: "Ghana",
                fullName: "the Republic of Ghana",
                activeDirectoryName: "Ghana",
                alpha2: CountryCode.GH,
                alpha3: CountryCodeAlpha3.GHA,
                numeric: 288),
            new Country(
                shortName: "Gibraltar",
                fullName: null,
                activeDirectoryName: "Gibraltar",
                alpha2: CountryCode.GI,
                alpha3: CountryCodeAlpha3.GIB,
                numeric: 292),
            new Country(
                shortName: "Greece",
                fullName: "the Hellenic Republic",
                activeDirectoryName: "Greece",
                alpha2: CountryCode.GR,
                alpha3: CountryCodeAlpha3.GRC,
                numeric: 300),
            new Country(
                shortName: "Greenland",
                fullName: null,
                activeDirectoryName: "Greenland",
                alpha2: CountryCode.GL,
                alpha3: CountryCodeAlpha3.GRL,
                numeric: 304),
            new Country(
                shortName: "Grenada",
                fullName: null,
                activeDirectoryName: "Grenada",
                alpha2: CountryCode.GD,
                alpha3: CountryCodeAlpha3.GRD,
                numeric: 308),
            new Country(
                shortName: "Guadeloupe",
                fullName: null,
                activeDirectoryName: "Guadeloupe",
                alpha2: CountryCode.GP,
                alpha3: CountryCodeAlpha3.GLP,
                numeric: 312),
            new Country(
                shortName: "Guam",
                fullName: null,
                activeDirectoryName: "Guam",
                alpha2: CountryCode.GU,
                alpha3: CountryCodeAlpha3.GUM,
                numeric: 316),
            new Country(
                shortName: "Guatemala",
                fullName: "the Republic of Guatemala",
                activeDirectoryName: "Guatemala",
                alpha2: CountryCode.GT,
                alpha3: CountryCodeAlpha3.GTM,
                numeric: 320),
            new Country(
                shortName: "Guernsey",
                fullName: null,
                activeDirectoryName: "Guernsey",
                alpha2: CountryCode.GG,
                alpha3: CountryCodeAlpha3.GGY,
                numeric: 831),
            new Country(
                shortName: "Guinea",
                fullName: "the Republic of Guinea",
                activeDirectoryName: "Guinea",
                alpha2: CountryCode.GN,
                alpha3: CountryCodeAlpha3.GIN,
                numeric: 324),
            new Country(
                shortName: "Guinea-Bissau",
                fullName: "the Republic of Guinea-Bissau",
                activeDirectoryName: "Guinea-Bissau",
                alpha2: CountryCode.GW,
                alpha3: CountryCodeAlpha3.GNB,
                numeric: 624),
            new Country(
                shortName: "Guyana",
                fullName: "the Republic of Guyana",
                activeDirectoryName: "Guyana",
                alpha2: CountryCode.GY,
                alpha3: CountryCodeAlpha3.GUY,
                numeric: 328),
            new Country(
                shortName: "Haiti",
                fullName: "the Republic of Haiti",
                activeDirectoryName: "Haiti",
                alpha2: CountryCode.HT,
                alpha3: CountryCodeAlpha3.HTI,
                numeric: 332),
            new Country(
                shortName: "Heard Island and McDonald Islands",
                fullName: null,
                activeDirectoryName: "Heard Island and McDonald Islands",
                alpha2: CountryCode.HM,
                alpha3: CountryCodeAlpha3.HMD,
                numeric: 334),
            new Country(
                shortName: "Holy See",
                fullName: null,
                activeDirectoryName: "Vatican City",
                alpha2: CountryCode.VA,
                alpha3: CountryCodeAlpha3.VAT,
                numeric: 336),
            new Country(
                shortName: "Honduras",
                fullName: "the Republic of Honduras",
                activeDirectoryName: "Honduras",
                alpha2: CountryCode.HN,
                alpha3: CountryCodeAlpha3.HND,
                numeric: 340),
            new Country(
                shortName: "Hong Kong",
                fullName: "the Hong Kong Special Administrative Region of China",
                activeDirectoryName: "Hong Kong SAR",
                alpha2: CountryCode.HK,
                alpha3: CountryCodeAlpha3.HKG,
                numeric: 344),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Howland Island",
                alpha2: CountryCode.None,
                alpha3: CountryCodeAlpha3.None,
                numeric: 581),
            new Country(
                shortName: "Hungary",
                fullName: null,
                activeDirectoryName: "Hungary",
                alpha2: CountryCode.HU,
                alpha3: CountryCodeAlpha3.HUN,
                numeric: 348),
            new Country(
                shortName: "Iceland",
                fullName: "the Republic of Iceland",
                activeDirectoryName: "Iceland",
                alpha2: CountryCode.IS,
                alpha3: CountryCodeAlpha3.ISL,
                numeric: 352),
            new Country(
                shortName: "India",
                fullName: "the Republic of India",
                activeDirectoryName: "India",
                alpha2: CountryCode.IN,
                alpha3: CountryCodeAlpha3.IND,
                numeric: 356),
            new Country(
                shortName: "Indonesia",
                fullName: "the Republic of Indonesia",
                activeDirectoryName: "Indonesia",
                alpha2: CountryCode.ID,
                alpha3: CountryCodeAlpha3.IDN,
                numeric: 360),
            new Country(
                shortName: "Iran (Islamic Republic of)",
                fullName: "the Islamic Republic of Iran",
                activeDirectoryName: "Iran",
                alpha2: CountryCode.IR,
                alpha3: CountryCodeAlpha3.IRN,
                numeric: 364),
            new Country(
                shortName: "Iraq",
                fullName: "the Republic of Iraq",
                activeDirectoryName: "Iraq",
                alpha2: CountryCode.IQ,
                alpha3: CountryCodeAlpha3.IRQ,
                numeric: 368),
            new Country(
                shortName: "Ireland",
                fullName: null,
                activeDirectoryName: "Ireland",
                alpha2: CountryCode.IE,
                alpha3: CountryCodeAlpha3.IRL,
                numeric: 372),
            new Country(
                shortName: "Isle of Man",
                fullName: null,
                activeDirectoryName: "Man, Isle of",
                alpha2: CountryCode.IM,
                alpha3: CountryCodeAlpha3.IMN,
                numeric: 833),
            new Country(
                shortName: "Israel",
                fullName: "the State of Israel",
                activeDirectoryName: "Israel",
                alpha2: CountryCode.IL,
                alpha3: CountryCodeAlpha3.ISR,
                numeric: 376),
            new Country(
                shortName: "Italy",
                fullName: "the Republic of Italy",
                activeDirectoryName: "Italy",
                alpha2: CountryCode.IT,
                alpha3: CountryCodeAlpha3.ITA,
                numeric: 380),
            new Country(
                shortName: "Jamaica",
                fullName: null,
                activeDirectoryName: "Jamaica",
                alpha2: CountryCode.JM,
                alpha3: CountryCodeAlpha3.JAM,
                numeric: 388),
            new Country(
                shortName: "Japan",
                fullName: null,
                activeDirectoryName: "Japan",
                alpha2: CountryCode.JP,
                alpha3: CountryCodeAlpha3.JPN,
                numeric: 392),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Jarvis Island",
                alpha2: CountryCode.None,
                alpha3: CountryCodeAlpha3.None,
                numeric: 581),
            new Country(
                shortName: "Jersey",
                fullName: null,
                activeDirectoryName: "Jersey",
                alpha2: CountryCode.JE,
                alpha3: CountryCodeAlpha3.JEY,
                numeric: 832),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Johnston Atoll",
                alpha2: CountryCode.None,
                alpha3: CountryCodeAlpha3.None,
                numeric: 581),
            new Country(
                shortName: "Jordan",
                fullName: "the Hashemite Kingdom of Jordan",
                activeDirectoryName: "Jordan",
                alpha2: CountryCode.JO,
                alpha3: CountryCodeAlpha3.JOR,
                numeric: 400),
            new Country(
                shortName: "Kazakhstan",
                fullName: "the Republic of Kazakhstan",
                activeDirectoryName: "Kazakhstan",
                alpha2: CountryCode.KZ,
                alpha3: CountryCodeAlpha3.KAZ,
                numeric: 398),
            new Country(
                shortName: "Kenya",
                fullName: "the Republic of Kenya",
                activeDirectoryName: "Kenya",
                alpha2: CountryCode.KE,
                alpha3: CountryCodeAlpha3.KEN,
                numeric: 404),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Kingman Reef",
                alpha2: CountryCode.None,
                alpha3: CountryCodeAlpha3.None,
                numeric: 581),
            new Country(
                shortName: "Kiribati",
                fullName: "the Republic of Kiribati",
                activeDirectoryName: "Kiribati",
                alpha2: CountryCode.KI,
                alpha3: CountryCodeAlpha3.KIR,
                numeric: 296),
            new Country(
                shortName: "Korea (Democratic People's Republic of)",
                fullName: "the Democratic People's Republic of Korea",
                activeDirectoryName: "North Korea",
                alpha2: CountryCode.KP,
                alpha3: CountryCodeAlpha3.PRK,
                numeric: 408),
            new Country(
                shortName: "Korea, Republic of",
                fullName: "the Republic of Korea",
                activeDirectoryName: "Korea",
                alpha2: CountryCode.KR,
                alpha3: CountryCodeAlpha3.KOR,
                numeric: 410),
            new Country(
                shortName: "Kuwait",
                fullName: "the State of Kuwait",
                activeDirectoryName: "Kuwait",
                alpha2: CountryCode.KW,
                alpha3: CountryCodeAlpha3.KWT,
                numeric: 414),
            new Country(
                shortName: "Kyrgyzstan",
                fullName: "the Kyrgyz Republic",
                activeDirectoryName: "Kyrgyzstan",
                alpha2: CountryCode.KG,
                alpha3: CountryCodeAlpha3.KGZ,
                numeric: 417),
            new Country(
                shortName: "Lao People's Democratic Republic",
                fullName: "the Lao People's Democratic Republic",
                activeDirectoryName: "Laos",
                alpha2: CountryCode.LA,
                alpha3: CountryCodeAlpha3.LAO,
                numeric: 418),
            new Country(
                shortName: "Latvia",
                fullName: "the Republic of Latvia",
                activeDirectoryName: "Latvia",
                alpha2: CountryCode.LV,
                alpha3: CountryCodeAlpha3.LVA,
                numeric: 428),
            new Country(
                shortName: "Lebanon",
                fullName: "the Lebanese Republic",
                activeDirectoryName: "Lebanon",
                alpha2: CountryCode.LB,
                alpha3: CountryCodeAlpha3.LBN,
                numeric: 422),
            new Country(
                shortName: "Lesotho",
                fullName: "the Kingdom of Lesotho",
                activeDirectoryName: "Lesotho",
                alpha2: CountryCode.LS,
                alpha3: CountryCodeAlpha3.LSO,
                numeric: 426),
            new Country(
                shortName: "Liberia",
                fullName: "the Republic of Liberia",
                activeDirectoryName: "Liberia",
                alpha2: CountryCode.LR,
                alpha3: CountryCodeAlpha3.LBR,
                numeric: 430),
            new Country(
                shortName: "Libya",
                fullName: null,
                activeDirectoryName: "Libya",
                alpha2: CountryCode.LY,
                alpha3: CountryCodeAlpha3.LBY,
                numeric: 434),
            new Country(
                shortName: "Liechtenstein",
                fullName: "the Principality of Liechtenstein",
                activeDirectoryName: "Liechtenstein",
                alpha2: CountryCode.LI,
                alpha3: CountryCodeAlpha3.LIE,
                numeric: 438),
            new Country(
                shortName: "Lithuania",
                fullName: "the Republic of Lithuania",
                activeDirectoryName: "Lithuania",
                alpha2: CountryCode.LT,
                alpha3: CountryCodeAlpha3.LTU,
                numeric: 440),
            new Country(
                shortName: "Luxembourg",
                fullName: "the Grand Duchy of Luxembourg",
                activeDirectoryName: "Luxembourg",
                alpha2: CountryCode.LU,
                alpha3: CountryCodeAlpha3.LUX,
                numeric: 442),
            new Country(
                shortName: "Macao",
                fullName: "Macao Special Administrative Region of China",
                activeDirectoryName: "Macao SAR",
                alpha2: CountryCode.MO,
                alpha3: CountryCodeAlpha3.MAC,
                numeric: 446),
            new Country(
                shortName: "Macedonia, the former Yugoslav Republic of",
                fullName: "the former Yugoslav Republic of Macedonia",
                activeDirectoryName: "Macedonia, Former Yugoslav Republic of",
                alpha2: CountryCode.MK,
                alpha3: CountryCodeAlpha3.MKD,
                numeric: 807),
            new Country(
                shortName: "Madagascar",
                fullName: "the Republic of Madagascar",
                activeDirectoryName: "Madagascar",
                alpha2: CountryCode.MG,
                alpha3: CountryCodeAlpha3.MDG,
                numeric: 450),
            new Country(
                shortName: "Malawi",
                fullName: "the Republic of Malawi",
                activeDirectoryName: "Malawi",
                alpha2: CountryCode.MW,
                alpha3: CountryCodeAlpha3.MWI,
                numeric: 454),
            new Country(
                shortName: "Malaysia",
                fullName: null,
                activeDirectoryName: "Malaysia",
                alpha2: CountryCode.MY,
                alpha3: CountryCodeAlpha3.MYS,
                numeric: 458),
            new Country(
                shortName: "Maldives",
                fullName: "the Republic of Maldives",
                activeDirectoryName: "Maldives",
                alpha2: CountryCode.MV,
                alpha3: CountryCodeAlpha3.MDV,
                numeric: 462),
            new Country(
                shortName: "Mali",
                fullName: "the Republic of Mali",
                activeDirectoryName: "Mali",
                alpha2: CountryCode.ML,
                alpha3: CountryCodeAlpha3.MLI,
                numeric: 466),
            new Country(
                shortName: "Malta",
                fullName: "the Republic of Malta",
                activeDirectoryName: "Malta",
                alpha2: CountryCode.MT,
                alpha3: CountryCodeAlpha3.MLT,
                numeric: 470),
            new Country(
                shortName: "Marshall Islands",
                fullName: "the Republic of the Marshall Islands",
                activeDirectoryName: "Marshall Islands",
                alpha2: CountryCode.MH,
                alpha3: CountryCodeAlpha3.MHL,
                numeric: 584),
            new Country(
                shortName: "Martinique",
                fullName: null,
                activeDirectoryName: "Martinique",
                alpha2: CountryCode.MQ,
                alpha3: CountryCodeAlpha3.MTQ,
                numeric: 474),
            new Country(
                shortName: "Mauritania",
                fullName: "the Islamic Republic of Mauritania",
                activeDirectoryName: "Mauritania",
                alpha2: CountryCode.MR,
                alpha3: CountryCodeAlpha3.MRT,
                numeric: 478),
            new Country(
                shortName: "Mauritius",
                fullName: "the Republic of Mauritius",
                activeDirectoryName: "Mauritius",
                alpha2: CountryCode.MU,
                alpha3: CountryCodeAlpha3.MUS,
                numeric: 480),
            new Country(
                shortName: "Mayotte",
                fullName: null,
                activeDirectoryName: "Mayotte",
                alpha2: CountryCode.YT,
                alpha3: CountryCodeAlpha3.MYT,
                numeric: 175),
            new Country(
                shortName: "Mexico",
                fullName: "the United Mexican States",
                activeDirectoryName: "Mexico",
                alpha2: CountryCode.MX,
                alpha3: CountryCodeAlpha3.MEX,
                numeric: 484),
            new Country(
                shortName: "Micronesia (Federated States of)",
                fullName: "the Federated States of Micronesia",
                activeDirectoryName: "Micronesia",
                alpha2: CountryCode.FM,
                alpha3: CountryCodeAlpha3.FSM,
                numeric: 583),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Midway Islands",
                alpha2: CountryCode.None,
                alpha3: CountryCodeAlpha3.None,
                numeric: 581),
            new Country(
                shortName: "Moldova, the Republic of",
                fullName: "the Republic of Moldova",
                activeDirectoryName: "Moldova",
                alpha2: CountryCode.MD,
                alpha3: CountryCodeAlpha3.MDA,
                numeric: 498),
            new Country(
                shortName: "Monaco",
                fullName: "the Principality of Monaco",
                activeDirectoryName: "Monaco",
                alpha2: CountryCode.MC,
                alpha3: CountryCodeAlpha3.MCO,
                numeric: 492),
            new Country(
                shortName: "Mongolia",
                fullName: null,
                activeDirectoryName: "Mongolia",
                alpha2: CountryCode.MN,
                alpha3: CountryCodeAlpha3.MNG,
                numeric: 496),
            new Country(
                shortName: "Montenegro",
                fullName: null,
                activeDirectoryName: "Montenegro",
                alpha2: CountryCode.ME,
                alpha3: CountryCodeAlpha3.MNE,
                numeric: 499),
            new Country(
                shortName: "Montserrat",
                fullName: null,
                activeDirectoryName: "Montserrat",
                alpha2: CountryCode.MS,
                alpha3: CountryCodeAlpha3.MSR,
                numeric: 500),
            new Country(
                shortName: "Morocco",
                fullName: "the Kingdom of Morocco",
                activeDirectoryName: "Morocco",
                alpha2: CountryCode.MA,
                alpha3: CountryCodeAlpha3.MAR,
                numeric: 504),
            new Country(
                shortName: "Mozambique",
                fullName: "the Republic of Mozambique",
                activeDirectoryName: "Mozambique",
                alpha2: CountryCode.MZ,
                alpha3: CountryCodeAlpha3.MOZ,
                numeric: 508),
            new Country(
                shortName: "Myanmar",
                fullName: "the Republic of the Union of Myanmar",
                activeDirectoryName: "Myanmar",
                alpha2: CountryCode.MM,
                alpha3: CountryCodeAlpha3.MMR,
                numeric: 104),
            new Country(
                shortName: "Namibia",
                fullName: "the Republic of Namibia",
                activeDirectoryName: "Namibia",
                alpha2: CountryCode.NA,
                alpha3: CountryCodeAlpha3.NAM,
                numeric: 516),
            new Country(
                shortName: "Nauru",
                fullName: "the Republic of Nauru",
                activeDirectoryName: "Nauru",
                alpha2: CountryCode.NR,
                alpha3: CountryCodeAlpha3.NRU,
                numeric: 520),
            new Country(
                shortName: "Nepal",
                fullName: "the Federal Democratic Republic of Nepal",
                activeDirectoryName: "Nepal",
                alpha2: CountryCode.NP,
                alpha3: CountryCodeAlpha3.NPL,
                numeric: 524),
            new Country(
                shortName: "Netherlands",
                fullName: "the Kingdom of the Netherlands",
                activeDirectoryName: "Netherlands",
                alpha2: CountryCode.NL,
                alpha3: CountryCodeAlpha3.NLD,
                numeric: 528),
            new Country(
                shortName: "New Caledonia",
                fullName: null,
                activeDirectoryName: "New Caledonia",
                alpha2: CountryCode.NC,
                alpha3: CountryCodeAlpha3.NCL,
                numeric: 540),
            new Country(
                shortName: "New Zealand",
                fullName: null,
                activeDirectoryName: "New Zealand",
                alpha2: CountryCode.NZ,
                alpha3: CountryCodeAlpha3.NZL,
                numeric: 554),
            new Country(
                shortName: "Nicaragua",
                fullName: "the Republic of Nicaragua",
                activeDirectoryName: "Nicaragua",
                alpha2: CountryCode.NI,
                alpha3: CountryCodeAlpha3.NIC,
                numeric: 558),
            new Country(
                shortName: "Niger",
                fullName: "the Republic of the Niger",
                activeDirectoryName: "Niger",
                alpha2: CountryCode.NE,
                alpha3: CountryCodeAlpha3.NER,
                numeric: 562),
            new Country(
                shortName: "Nigeria",
                fullName: "the Federal Republic of Nigeria",
                activeDirectoryName: "Nigeria",
                alpha2: CountryCode.NG,
                alpha3: CountryCodeAlpha3.NGA,
                numeric: 566),
            new Country(
                shortName: "Niue",
                fullName: null,
                activeDirectoryName: "Niue",
                alpha2: CountryCode.NU,
                alpha3: CountryCodeAlpha3.NIU,
                numeric: 570),
            new Country(
                shortName: "Norfolk Island",
                fullName: null,
                activeDirectoryName: "Norfolk Island",
                alpha2: CountryCode.NF,
                alpha3: CountryCodeAlpha3.NFK,
                numeric: 574),
            new Country(
                shortName: "Northern Mariana Islands",
                fullName: "the Commonwealth of the Northern Mariana Islands",
                activeDirectoryName: "Northern Mariana Islands",
                alpha2: CountryCode.MP,
                alpha3: CountryCodeAlpha3.MNP,
                numeric: 580),
            new Country(
                shortName: "Norway",
                fullName: "the Kingdom of Norway",
                activeDirectoryName: "Norway",
                alpha2: CountryCode.NO,
                alpha3: CountryCodeAlpha3.NOR,
                numeric: 578),
            new Country(
                shortName: "Oman",
                fullName: "the Sultanate of Oman",
                activeDirectoryName: "Oman",
                alpha2: CountryCode.OM,
                alpha3: CountryCodeAlpha3.OMN,
                numeric: 512),
            new Country(
                shortName: "Pakistan",
                fullName: "the Islamic Republic of Pakistan",
                activeDirectoryName: "Pakistan",
                alpha2: CountryCode.PK,
                alpha3: CountryCodeAlpha3.PAK,
                numeric: 586),
            new Country(
                shortName: "Palau",
                fullName: "the Republic of Palau",
                activeDirectoryName: "Palau",
                alpha2: CountryCode.PW,
                alpha3: CountryCodeAlpha3.PLW,
                numeric: 585),
            new Country(
                shortName: "Palestine, State of",
                fullName: "the State of Palestine",
                activeDirectoryName: "Palestinian Authority",
                alpha2: CountryCode.PS,
                alpha3: CountryCodeAlpha3.PSE,
                numeric: 275),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Palmyra Atoll",
                alpha2: CountryCode.None,
                alpha3: CountryCodeAlpha3.None,
                numeric: 581),
            new Country(
                shortName: "Panama",
                fullName: "the Republic of Panama",
                activeDirectoryName: "Panama",
                alpha2: CountryCode.PA,
                alpha3: CountryCodeAlpha3.PAN,
                numeric: 591),
            new Country(
                shortName: "Papua New Guinea",
                fullName: "the Independent State of Papua New Guinea",
                activeDirectoryName: "Papua New Guinea",
                alpha2: CountryCode.PG,
                alpha3: CountryCodeAlpha3.PNG,
                numeric: 598),
            new Country(
                shortName: "Paraguay",
                fullName: "the Republic of Paraguay",
                activeDirectoryName: "Paraguay",
                alpha2: CountryCode.PY,
                alpha3: CountryCodeAlpha3.PRY,
                numeric: 600),
            new Country(
                shortName: "Peru",
                fullName: "the Republic of Peru",
                activeDirectoryName: "Peru",
                alpha2: CountryCode.PE,
                alpha3: CountryCodeAlpha3.PER,
                numeric: 604),
            new Country(
                shortName: "Philippines",
                fullName: "the Republic of the Philippines",
                activeDirectoryName: "Philippines",
                alpha2: CountryCode.PH,
                alpha3: CountryCodeAlpha3.PHL,
                numeric: 608),
            new Country(
                shortName: "Pitcairn",
                fullName: null,
                activeDirectoryName: "Pitcairn Islands",
                alpha2: CountryCode.PN,
                alpha3: CountryCodeAlpha3.PCN,
                numeric: 612),
            new Country(
                shortName: "Poland",
                fullName: "the Republic of Poland",
                activeDirectoryName: "Poland",
                alpha2: CountryCode.PL,
                alpha3: CountryCodeAlpha3.POL,
                numeric: 616),
            new Country(
                shortName: "Portugal",
                fullName: "the Portuguese Republic",
                activeDirectoryName: "Portugal",
                alpha2: CountryCode.PT,
                alpha3: CountryCodeAlpha3.PRT,
                numeric: 620),
            new Country(
                shortName: "Puerto Rico",
                fullName: null,
                activeDirectoryName: "Puerto Rico",
                alpha2: CountryCode.PR,
                alpha3: CountryCodeAlpha3.PRI,
                numeric: 630),
            new Country(
                shortName: "Qatar",
                fullName: null,
                activeDirectoryName: "Qatar",
                alpha2: CountryCode.QA,
                alpha3: CountryCodeAlpha3.QAT,
                numeric: 634),
            new Country(
                shortName: "Réunion",
                fullName: null,
                activeDirectoryName: "Réunion",
                alpha2: CountryCode.RE,
                alpha3: CountryCodeAlpha3.REU,
                numeric: 638),
            new Country(
                shortName: "Romania",
                fullName: null,
                activeDirectoryName: "Romania",
                alpha2: CountryCode.RO,
                alpha3: CountryCodeAlpha3.ROU,
                numeric: 642),
            new Country(
                shortName: "Russian Federation",
                fullName: "the Russian Federation",
                activeDirectoryName: "Russia",
                alpha2: CountryCode.RU,
                alpha3: CountryCodeAlpha3.RUS,
                numeric: 643),
            new Country(
                shortName: "Rwanda",
                fullName: "the Republic of Rwanda",
                activeDirectoryName: "Rwanda",
                alpha2: CountryCode.RW,
                alpha3: CountryCodeAlpha3.RWA,
                numeric: 646),
            new Country(
                shortName: "Saint Barthélemy",
                fullName: null,
                activeDirectoryName: "Saint Barthélemy",
                alpha2: CountryCode.BL,
                alpha3: CountryCodeAlpha3.BLM,
                numeric: 652),
            new Country(
                shortName: "Saint Helena, Ascension and Tristan da Cunha",
                fullName: null,
                activeDirectoryName: "Saint Helena, Ascension and Tristan da Cunha",
                alpha2: CountryCode.SH,
                alpha3: CountryCodeAlpha3.SHN,
                numeric: 654),
            new Country(
                shortName: "Saint Kitts and Nevis",
                fullName: null,
                activeDirectoryName: "St. Kitts and Nevis",
                alpha2: CountryCode.KN,
                alpha3: CountryCodeAlpha3.KNA,
                numeric: 659),
            new Country(
                shortName: "Saint Lucia",
                fullName: null,
                activeDirectoryName: "St. Lucia",
                alpha2: CountryCode.LC,
                alpha3: CountryCodeAlpha3.LCA,
                numeric: 662),
            new Country(
                shortName: "Saint Martin (French part)",
                fullName: null,
                activeDirectoryName: "Saint Martin (French part)",
                alpha2: CountryCode.MF,
                alpha3: CountryCodeAlpha3.MAF,
                numeric: 663),
            new Country(
                shortName: "Saint Pierre and Miquelon",
                fullName: null,
                activeDirectoryName: "St. Pierre and Miquelon",
                alpha2: CountryCode.PM,
                alpha3: CountryCodeAlpha3.SPM,
                numeric: 666),
            new Country(
                shortName: "Saint Vincent and the Grenadines",
                fullName: null,
                activeDirectoryName: "St. Vincent and the Grenadines",
                alpha2: CountryCode.VC,
                alpha3: CountryCodeAlpha3.VCT,
                numeric: 670),
            new Country(
                shortName: "Samoa",
                fullName: "the Independent State of Samoa",
                activeDirectoryName: "Samoa",
                alpha2: CountryCode.WS,
                alpha3: CountryCodeAlpha3.WSM,
                numeric: 882),
            new Country(
                shortName: "San Marino",
                fullName: "the Republic of San Marino",
                activeDirectoryName: "San Marino",
                alpha2: CountryCode.SM,
                alpha3: CountryCodeAlpha3.SMR,
                numeric: 674),
            new Country(
                shortName: "Sao Tome and Principe",
                fullName: "the Democratic Republic of Sao Tome and Principe",
                activeDirectoryName: "São Tomé and Príncipe",
                alpha2: CountryCode.ST,
                alpha3: CountryCodeAlpha3.STP,
                numeric: 678),
            new Country(
                shortName: "Saudi Arabia",
                fullName: "the Kingdom of Saudi Arabia",
                activeDirectoryName: "Saudi Arabia",
                alpha2: CountryCode.SA,
                alpha3: CountryCodeAlpha3.SAU,
                numeric: 682),
            new Country(
                shortName: "Senegal",
                fullName: "the Republic of Senegal",
                activeDirectoryName: "Senegal",
                alpha2: CountryCode.SN,
                alpha3: CountryCodeAlpha3.SEN,
                numeric: 686),
            new Country(
                shortName: "Serbia",
                fullName: "the Republic of Serbia",
                activeDirectoryName: "Serbia",
                alpha2: CountryCode.RS,
                alpha3: CountryCodeAlpha3.SRB,
                numeric: 688),
             new Country(
                 shortName: null,
                 fullName: null,
                 activeDirectoryName: "Serbia and Montenegro (Former)",
                 alpha2: CountryCode.CS,
                 alpha3: CountryCodeAlpha3.SCG,
                 numeric: 891),
             new Country(
                 shortName: "Seychelles",
                 fullName: "the Republic of Seychelles",
                 activeDirectoryName: "Seychelles",
                 alpha2: CountryCode.SC,
                 alpha3: CountryCodeAlpha3.SYC,
                 numeric: 690),
            new Country(
                shortName: "Sierra Leone",
                fullName: "the Republic of Sierra Leone",
                activeDirectoryName: "Sierra Leone",
                alpha2: CountryCode.SL,
                alpha3: CountryCodeAlpha3.SLE,
                numeric: 694),
            new Country(
                shortName: "Singapore",
                fullName: "the Republic of Singapore",
                activeDirectoryName: "Singapore",
                alpha2: CountryCode.SG,
                alpha3: CountryCodeAlpha3.SGP,
                numeric: 702),
            new Country(
                shortName: "Sint Maarten (Dutch part)",
                fullName: null,
                activeDirectoryName: "Sint Maarten (Dutch part)",
                alpha2: CountryCode.SX,
                alpha3: CountryCodeAlpha3.SXM,
                numeric: 534),
            new Country(
                shortName: "Slovakia",
                fullName: "the Slovak Republic",
                activeDirectoryName: "Slovakia",
                alpha2: CountryCode.SK,
                alpha3: CountryCodeAlpha3.SVK,
                numeric: 703),
            new Country(
                shortName: "Slovenia",
                fullName: "the Republic of Slovenia",
                activeDirectoryName: "Slovenia",
                alpha2: CountryCode.SI,
                alpha3: CountryCodeAlpha3.SVN,
                numeric: 705),
            new Country(
                shortName: "Solomon Islands",
                fullName: null,
                activeDirectoryName: "Solomon Islands",
                alpha2: CountryCode.SB,
                alpha3: CountryCodeAlpha3.SLB,
                numeric: 90),
            new Country(
                shortName: "Somalia",
                fullName: "the Federal Republic of Somalia",
                activeDirectoryName: "Somalia",
                alpha2: CountryCode.SO,
                alpha3: CountryCodeAlpha3.SOM,
                numeric: 706),
            new Country(
                shortName: "South Africa",
                fullName: "the Republic of South Africa",
                activeDirectoryName: "South Africa",
                alpha2: CountryCode.ZA,
                alpha3: CountryCodeAlpha3.ZAF,
                numeric: 710),
            new Country(
                shortName: "South Georgia and the South Sandwich Islands",
                fullName: null,
                activeDirectoryName: "South Georgia and the South Sandwich Islands",
                alpha2: CountryCode.GS,
                alpha3: CountryCodeAlpha3.SGS,
                numeric: 239),
            new Country(
                shortName: "South Sudan",
                fullName: "the Republic of South Sudan",
                activeDirectoryName: "South Sudan",
                alpha2: CountryCode.SS,
                alpha3: CountryCodeAlpha3.SSD,
                numeric: 728),
            new Country(
                shortName: "Spain",
                fullName: "the Kingdom of Spain",
                activeDirectoryName: "Spain",
                alpha2: CountryCode.ES,
                alpha3: CountryCodeAlpha3.ESP,
                numeric: 724),
            new Country(
                shortName: "Sri Lanka",
                fullName: "the Democratic Socialist Republic of Sri Lanka",
                activeDirectoryName: "Sri Lanka",
                alpha2: CountryCode.LK,
                alpha3: CountryCodeAlpha3.LKA,
                numeric: 144),
            new Country(
                shortName: "Sudan",
                fullName: "the Republic of the Sudan",
                activeDirectoryName: "Sudan",
                alpha2: CountryCode.SD,
                alpha3: CountryCodeAlpha3.SDN,
                numeric: 729),
            new Country(
                shortName: "Suriname",
                fullName: "the Republic of Suriname",
                activeDirectoryName: "Suriname",
                alpha2: CountryCode.SR,
                alpha3: CountryCodeAlpha3.SUR,
                numeric: 740),
            new Country(
                shortName: "Svalbard and Jan Mayen",
                fullName: null,
                activeDirectoryName: "Svalbard",
                alpha2: CountryCode.SJ,
                alpha3: CountryCodeAlpha3.SJM,
                numeric: 744),
            new Country(
                shortName: "Swaziland",
                fullName: "the Kingdom of Swaziland",
                activeDirectoryName: "Swaziland",
                alpha2: CountryCode.SZ,
                alpha3: CountryCodeAlpha3.SWZ,
                numeric: 748),
            new Country(
                shortName: "Sweden",
                fullName: "the Kingdom of Sweden",
                activeDirectoryName: "Sweden",
                alpha2: CountryCode.SE,
                alpha3: CountryCodeAlpha3.SWE,
                numeric: 752),
            new Country(
                shortName: "Switzerland",
                fullName: "the Swiss Confederation",
                activeDirectoryName: "Switzerland",
                alpha2: CountryCode.CH,
                alpha3: CountryCodeAlpha3.CHE,
                numeric: 756),
            new Country(
                shortName: "Syrian Arab Republic",
                fullName: "the Syrian Arab Republic",
                activeDirectoryName: "Syria",
                alpha2: CountryCode.SY,
                alpha3: CountryCodeAlpha3.SYR,
                numeric: 760),
            new Country(
                shortName: "Taiwan, Province of China",
                fullName: null,
                activeDirectoryName: "Taiwan",
                alpha2: CountryCode.TW,
                alpha3: CountryCodeAlpha3.TWN,
                numeric: 158),
            new Country(
                shortName: "Tajikistan",
                fullName: "the Republic of Tajikistan",
                activeDirectoryName: "Tajikistan",
                alpha2: CountryCode.TJ,
                alpha3: CountryCodeAlpha3.TJK,
                numeric: 762),
            new Country(
                shortName: "Tanzania, United Republic of",
                fullName: "the United Republic of Tanzania",
                activeDirectoryName: "Tanzania",
                alpha2: CountryCode.TZ,
                alpha3: CountryCodeAlpha3.TZA,
                numeric: 834),
            new Country(
                shortName: "Thailand",
                fullName: "the Kingdom of Thailand",
                activeDirectoryName: "Thailand",
                alpha2: CountryCode.TH,
                alpha3: CountryCodeAlpha3.THA,
                numeric: 764),
            new Country(
                shortName: "Timor-Leste",
                fullName: "the Democratic Republic of Timor-Leste",
                activeDirectoryName: "Democratic Republic of Timor-Leste",
                alpha2: CountryCode.TL,
                alpha3: CountryCodeAlpha3.TLS,
                numeric: 626),
            new Country(
                shortName: "Togo",
                fullName: "the Togolese Republic",
                activeDirectoryName: "Togo",
                alpha2: CountryCode.TG,
                alpha3: CountryCodeAlpha3.TGO,
                numeric: 768),
            new Country(
                shortName: "Tokelau",
                fullName: null,
                activeDirectoryName: "Tokelau",
                alpha2: CountryCode.TK,
                alpha3: CountryCodeAlpha3.TKL,
                numeric: 772),
            new Country(
                shortName: "Tonga",
                fullName: "the Kingdom of Tonga",
                activeDirectoryName: "Tonga",
                alpha2: CountryCode.TO,
                alpha3: CountryCodeAlpha3.TON,
                numeric: 776),
            new Country(
                shortName: "Trinidad and Tobago",
                fullName: "the Republic of Trinidad and Tobago",
                activeDirectoryName: "Trinidad and Tobago",
                alpha2: CountryCode.TT,
                alpha3: CountryCodeAlpha3.TTO,
                numeric: 780),
            new Country(
                shortName: "Tunisia",
                fullName: "the Republic of Tunisia",
                activeDirectoryName: "Tunisia",
                alpha2: CountryCode.TN,
                alpha3: CountryCodeAlpha3.TUN,
                numeric: 788),
            new Country(
                shortName: "Turkey",
                fullName: "the Republic of Turkey",
                activeDirectoryName: "Turkey",
                alpha2: CountryCode.TR,
                alpha3: CountryCodeAlpha3.TUR,
                numeric: 792),
            new Country(
                shortName: "Turkmenistan",
                fullName: null,
                activeDirectoryName: "Turkmenistan",
                alpha2: CountryCode.TM,
                alpha3: CountryCodeAlpha3.TKM,
                numeric: 795),
            new Country(
                shortName: "Turks and Caicos Islands",
                fullName: null,
                activeDirectoryName: "Turks and Caicos Islands",
                alpha2: CountryCode.TC,
                alpha3: CountryCodeAlpha3.TCA,
                numeric: 796),
            new Country(
                shortName: "Tuvalu",
                fullName: null,
                activeDirectoryName: "Tuvalu",
                alpha2: CountryCode.TV,
                alpha3: CountryCodeAlpha3.TUV,
                numeric: 798),
            new Country(
                shortName: "Uganda",
                fullName: "the Republic of Uganda",
                activeDirectoryName: "Uganda",
                alpha2: CountryCode.UG,
                alpha3: CountryCodeAlpha3.UGA,
                numeric: 800),
            new Country(
                shortName: "Ukraine",
                fullName: null,
                activeDirectoryName: "Ukraine",
                alpha2: CountryCode.UA,
                alpha3: CountryCodeAlpha3.UKR,
                numeric: 804),
            new Country(
                shortName: "United Arab Emirates",
                fullName: "the United Arab Emirates",
                activeDirectoryName: "United Arab Emirates",
                alpha2: CountryCode.AE,
                alpha3: CountryCodeAlpha3.ARE,
                numeric: 784),
            new Country(
                shortName: "United Kingdom of Great Britain and Northern Ireland",
                fullName: "the United Kingdom of Great Britain and Northern Ireland",
                activeDirectoryName: "United Kingdom",
                alpha2: CountryCode.GB,
                alpha3: CountryCodeAlpha3.GBR,
                numeric: 826),
            new Country(
                shortName: "United States Minor Outlying Islands",
                fullName: null,
                activeDirectoryName: "U.S. Minor Outlying Islands",
                alpha2: CountryCode.UM,
                alpha3: CountryCodeAlpha3.UMI,
                numeric: 581),
            new Country(
                shortName: "United States of America",
                fullName: "the United States of America",
                activeDirectoryName: "United States",
                alpha2: CountryCode.US,
                alpha3: CountryCodeAlpha3.USA,
                numeric: 840),
            new Country(
                shortName: "Uruguay",
                fullName: "the Eastern Republic of Uruguay",
                activeDirectoryName: "Uruguay",
                alpha2: CountryCode.UY,
                alpha3: CountryCodeAlpha3.URY,
                numeric: 858),
            new Country(
                shortName: "Uzbekistan",
                fullName: "the Republic of Uzbekistan",
                activeDirectoryName: "Uzbekistan",
                alpha2: CountryCode.UZ,
                alpha3: CountryCodeAlpha3.UZB,
                numeric: 860),
            new Country(
                shortName: "Vanuatu",
                fullName: "the Republic of Vanuatu",
                activeDirectoryName: "Vanuatu",
                alpha2: CountryCode.VU,
                alpha3: CountryCodeAlpha3.VUT,
                numeric: 548),
            new Country(
                shortName: "Venezuela (Bolivarian Republic of)",
                fullName: "the Bolivarian Republic of Venezuela",
                activeDirectoryName: "Bolivarian Republic of Venezuela",
                alpha2: CountryCode.VE,
                alpha3: CountryCodeAlpha3.VEN,
                numeric: 862),
            new Country(
                shortName: "Viet Nam",
                fullName: "the Socialist Republic of Viet Nam",
                activeDirectoryName: "Vietnam",
                alpha2: CountryCode.VN,
                alpha3: CountryCodeAlpha3.VNM,
                numeric: 704),
            new Country(
                shortName: "Virgin Islands (British)",
                fullName: "British Virgin Islands (the)",
                activeDirectoryName: "Virgin Islands, British",
                alpha2: CountryCode.VG,
                alpha3: CountryCodeAlpha3.VGB,
                numeric: 92),
            new Country(
                shortName: "Virgin Islands (U.S.)",
                fullName: "the Virgin Islands of the United States",
                activeDirectoryName: "Virgin Islands",
                alpha2: CountryCode.VI,
                alpha3: CountryCodeAlpha3.VIR,
                numeric: 850),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Wake Island",
                alpha2: CountryCode.None,
                alpha3: CountryCodeAlpha3.None,
                numeric: 581),
            new Country(
                shortName: "Wallis and Futuna",
                fullName: "Wallis and Futuna Islands",
                activeDirectoryName: "Wallis and Futuna",
                alpha2: CountryCode.WF,
                alpha3: CountryCodeAlpha3.WLF,
                numeric: 876),
            new Country(
                shortName: "Western Sahara",
                fullName: null,
                activeDirectoryName: null,
                alpha2: CountryCode.EH,
                alpha3: CountryCodeAlpha3.ESH,
                numeric: 732),
            new Country(
                shortName: "Yemen",
                fullName: "the Republic of Yemen",
                activeDirectoryName: "Yemen",
                alpha2: CountryCode.YE,
                alpha3: CountryCodeAlpha3.YEM,
                numeric: 887),
            new Country(
                shortName: "Zambia",
                fullName: "the Republic of Zambia",
                activeDirectoryName: "Zambia",
                alpha2: CountryCode.ZM,
                alpha3: CountryCodeAlpha3.ZMB,
                numeric: 894),
            new Country(
                shortName: "Zimbabwe",
                fullName: "the Republic of Zimbabwe",
                activeDirectoryName: "Zimbabwe",
                alpha2: CountryCode.ZW,
                alpha3: CountryCodeAlpha3.ZWE,
                numeric: 716)
        }.AsReadOnly();
    }
}
