namespace Bia.Countries.Iso3166
{
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public static partial class Countries
    {
        public static readonly ReadOnlyCollection<Country> CountryList = new List<Country>()
        {
            new Country(
                shortName: "Afghanistan",
                fullName: "the Islamic Republic of Afghanistan",
                activeDirectoryName: "Afghanistan",
                alpha2: "AF",
                alpha3: "AFG",
                numeric: 4),
            new Country(
                shortName: "Åland Islands",
                fullName: null,
                activeDirectoryName: "Åland Islands",
                alpha2: "AX",
                alpha3: "ALA",
                numeric: 248),
            new Country(
                shortName: "Albania",
                fullName: "the Republic of Albania",
                activeDirectoryName: "Albania",
                alpha2: "AL",
                alpha3: "ALB",
                numeric: 8),
            new Country(
                shortName: "Algeria",
                fullName: "the People's Democratic Republic of Algeria",
                activeDirectoryName: "Algeria",
                alpha2: "DZ",
                alpha3: "DZA",
                numeric: 12),
            new Country(
                shortName: "American Samoa",
                fullName: null,
                activeDirectoryName: "American Samoa",
                alpha2: "AS",
                alpha3: "ASM",
                numeric: 16),
            new Country(
                shortName: "Andorra",
                fullName: "the Principality of Andorra",
                activeDirectoryName: "Andorra",
                alpha2: "AD",
                alpha3: "AND",
                numeric: 20),
            new Country(
                shortName: "Angola",
                fullName: "the Republic of Angola",
                activeDirectoryName: "Angola",
                alpha2: "AO",
                alpha3: "AGO",
                numeric: 24),
            new Country(
                shortName: "Anguilla",
                fullName: null,
                activeDirectoryName: "Anguilla",
                alpha2: "AI",
                alpha3: "AIA",
                numeric: 660),
            new Country(
                shortName: "Antarctica",
                fullName: null,
                activeDirectoryName: "Antarctica",
                alpha2: "AQ",
                alpha3: "ATA",
                numeric: 10),
            new Country(
                shortName: "Antigua and Barbuda",
                fullName: null,
                activeDirectoryName: "Antigua and Barbuda",
                alpha2: "AG",
                alpha3: "ATG",
                numeric: 28),
            new Country(
                shortName: "Argentina",
                fullName: "the Argentine Republic",
                activeDirectoryName: "Argentina",
                alpha2: "AR",
                alpha3: "ARG",
                numeric: 32),
            new Country(
                shortName: "Armenia",
                fullName: "the Republic of Armenia",
                activeDirectoryName: "Armenia",
                alpha2: "AM",
                alpha3: "ARM",
                numeric: 51),
            new Country(
                shortName: "Aruba",
                fullName: null,
                activeDirectoryName: "Aruba",
                alpha2: "AW",
                alpha3: "ABW",
                numeric: 533),
            new Country(
                shortName: "Australia",
                fullName: null,
                activeDirectoryName: "Australia",
                alpha2: "AU",
                alpha3: "AUS",
                numeric: 36),
            new Country(
                shortName: "Austria",
                fullName: "the Republic of Austria",
                activeDirectoryName: "Austria",
                alpha2: "AT",
                alpha3: "AUT",
                numeric: 40),
            new Country(
                shortName: "Azerbaijan",
                fullName: "the Republic of Azerbaijan",
                activeDirectoryName: "Azerbaijan",
                alpha2: "AZ",
                alpha3: "AZE",
                numeric: 31),
            new Country(
                shortName: "Bahamas",
                fullName: "the Commonwealth of the Bahamas",
                activeDirectoryName: "Bahamas, The",
                alpha2: "BS",
                alpha3: "BHS",
                numeric: 44),
            new Country(
                shortName: "Bahrain",
                fullName: "the Kingdom of Bahrain",
                activeDirectoryName: "Bahrain",
                alpha2: "BH",
                alpha3: "BHR",
                numeric: 48),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Baker Island",
                alpha2: null,
                alpha3: null,
                numeric: 581),
            new Country(
                shortName: "Bangladesh",
                fullName: "the People's Republic of Bangladesh",
                activeDirectoryName: "Bangladesh",
                alpha2: "BD",
                alpha3: "BGD",
                numeric: 50),
            new Country(
                shortName: "Barbados",
                fullName: null,
                activeDirectoryName: "Barbados",
                alpha2: "BB",
                alpha3: "BRB",
                numeric: 52),
            new Country(
                shortName: "Belarus",
                fullName: "the Republic of Belarus",
                activeDirectoryName: "Belarus",
                alpha2: "BY",
                alpha3: "BLR",
                numeric: 112),
            new Country(
                shortName: "Belgium",
                fullName: "the Kingdom of Belgium",
                activeDirectoryName: "Belgium",
                alpha2: "BE",
                alpha3: "BEL",
                numeric: 56),
            new Country(
                shortName: "Belize",
                fullName: null,
                activeDirectoryName: "Belize",
                alpha2: "BZ",
                alpha3: "BLZ",
                numeric: 84),
            new Country(
                shortName: "Benin",
                fullName: "the Republic of Benin",
                activeDirectoryName: "Benin",
                alpha2: "BJ",
                alpha3: "BEN",
                numeric: 204),
            new Country(
                shortName: "Bermuda",
                fullName: null,
                activeDirectoryName: "Bermuda",
                alpha2: "BM",
                alpha3: "BMU",
                numeric: 60),
            new Country(
                shortName: "Bhutan",
                fullName: "the Kingdom of Bhutan",
                activeDirectoryName: "Bhutan",
                alpha2: "BT",
                alpha3: "BTN",
                numeric: 64),
            new Country(
                shortName: "Bolivia (Plurinational State of)",
                fullName: "the Plurinational State of Bolivia",
                activeDirectoryName: "Bolivia",
                alpha2: "BO",
                alpha3: "BOL",
                numeric: 68),
            new Country(
                shortName: "Bonaire, Sint Eustatius and Saba",
                fullName: null,
                activeDirectoryName: "Bonaire, Sint Eustatius and Saba",
                alpha2: "BQ",
                alpha3: "BES",
                numeric: 535),
            new Country(
                shortName: "Bosnia and Herzegovina",
                fullName: null,
                activeDirectoryName: "Bosnia and Herzegovina",
                alpha2: "BA",
                alpha3: "BIH",
                numeric: 70),
            new Country(
                shortName: "Botswana",
                fullName: "the Republic of Botswana",
                activeDirectoryName: "Botswana",
                alpha2: "BW",
                alpha3: "BWA",
                numeric: 72),
            new Country(
                shortName: "Bouvet Island",
                fullName: null,
                activeDirectoryName: "Bouvet Island",
                alpha2: "BV",
                alpha3: "BVT",
                numeric: 74),
            new Country(
                shortName: "Brazil",
                fullName: "the Federative Republic of Brazil",
                activeDirectoryName: "Brazil",
                alpha2: "BR",
                alpha3: "BRA",
                numeric: 76),
            new Country(
                shortName: "British Indian Ocean Territory",
                fullName: "the British Indian Ocean Territory",
                activeDirectoryName: "British Indian Ocean Territory",
                alpha2: "IO",
                alpha3: "IOT",
                numeric: 86),
            new Country(
                shortName: "Brunei Darussalam",
                fullName: null,
                activeDirectoryName: "Brunei",
                alpha2: "BN",
                alpha3: "BRN",
                numeric: 96),
            new Country(
                shortName: "Bulgaria",
                fullName: "the Republic of Bulgaria",
                activeDirectoryName: "Bulgaria",
                alpha2: "BG",
                alpha3: "BGR",
                numeric: 100),
            new Country(
                shortName: "Burkina Faso",
                fullName: null,
                activeDirectoryName: "Burkina Faso",
                alpha2: "BF",
                alpha3: "BFA",
                numeric: 854),
            new Country(
                shortName: "Burundi",
                fullName: "the Republic of Burundi",
                activeDirectoryName: "Burundi",
                alpha2: "BI",
                alpha3: "BDI",
                numeric: 108),
            new Country(
                shortName: "Cabo Verde",
                fullName: "the Republic of Cabo Verde",
                activeDirectoryName: "Cape Verde",
                alpha2: "CV",
                alpha3: "CPV",
                numeric: 132),
            new Country(
                shortName: "Cambodia",
                fullName: "the Kingdom of Cambodia",
                activeDirectoryName: "Cambodia",
                alpha2: "KH",
                alpha3: "KHM",
                numeric: 116),
            new Country(
                shortName: "Cameroon",
                fullName: "the Republic of Cameroon",
                activeDirectoryName: "Cameroon",
                alpha2: "CM",
                alpha3: "CMR",
                numeric: 120),
            new Country(
                shortName: "Canada",
                fullName: null,
                activeDirectoryName: "Canada",
                alpha2: "CA",
                alpha3: "CAN",
                numeric: 124),
            new Country(
                shortName: "Cayman Islands",
                fullName: "the Cayman Islands",
                activeDirectoryName: "Cayman Islands",
                alpha2: "KY",
                alpha3: "CYM",
                numeric: 136),
            new Country(
                shortName: "Central African Republic",
                fullName: "the Central African Republic",
                activeDirectoryName: "Central African Republic",
                alpha2: "CF",
                alpha3: "CAF",
                numeric: 140),
            new Country(
                shortName: "Chad",
                fullName: "the Republic of Chad",
                activeDirectoryName: "Chad",
                alpha2: "TD",
                alpha3: "TCD",
                numeric: 148),
            new Country(
                shortName: "Chile",
                fullName: "the Republic of Chile",
                activeDirectoryName: "Chile",
                alpha2: "CL",
                alpha3: "CHL",
                numeric: 152),
            new Country(
                shortName: "China",
                fullName: "the People's Republic of China",
                activeDirectoryName: "China",
                alpha2: "CN",
                alpha3: "CHN",
                numeric: 156),
            new Country(
                shortName: "Christmas Island",
                fullName: null,
                activeDirectoryName: "Christmas Island",
                alpha2: "CX",
                alpha3: "CXR",
                numeric: 162),
            new Country(
                shortName: "Cocos (Keeling) Islands",
                fullName: "the Cocos (Keeling) Islands",
                activeDirectoryName: "Cocos (Keeling) Islands",
                alpha2: "CC",
                alpha3: "CCK",
                numeric: 166),
            new Country(
                shortName: "Colombia",
                fullName: "the Republic of Colombia",
                activeDirectoryName: "Colombia",
                alpha2: "CO",
                alpha3: "COL",
                numeric: 170),
            new Country(
                shortName: "Comoros",
                fullName: "the Union of the Comoros",
                activeDirectoryName: "Comoros",
                alpha2: "KM",
                alpha3: "COM",
                numeric: 174),
            new Country(
                shortName: "Congo, Democratic Republic of the",
                fullName: "the Democratic Republic of the Congo",
                activeDirectoryName: "Congo (DRC)",
                alpha2: "CD",
                alpha3: "COD",
                numeric: 180),
            new Country(
                shortName: "Congo",
                fullName: "the Republic of the Congo",
                activeDirectoryName: "Congo",
                alpha2: "CG",
                alpha3: "COG",
                numeric: 178),
            new Country(
                shortName: "Cook Islands",
                fullName: null,
                activeDirectoryName: "Cook Islands",
                alpha2: "CK",
                alpha3: "COK",
                numeric: 184),
            new Country(
                shortName: "Costa Rica",
                fullName: "the Republic of Costa Rica",
                activeDirectoryName: "Costa Rica",
                alpha2: "CR",
                alpha3: "CRI",
                numeric: 188),
            new Country(
                shortName: "Côte d'Ivoire",
                fullName: "the Republic of Côte d'Ivoire",
                activeDirectoryName: "Côte d'Ivoire",
                alpha2: "CI",
                alpha3: "CIV",
                numeric: 384),
            new Country(
                shortName: "Croatia",
                fullName: "the Republic of Croatia",
                activeDirectoryName: "Croatia",
                alpha2: "HR",
                alpha3: "HRV",
                numeric: 191),
            new Country(
                shortName: "Cuba",
                fullName: "the Republic of Cuba",
                activeDirectoryName: "Cuba",
                alpha2: "CU",
                alpha3: "CUB",
                numeric: 192),
            new Country(
                shortName: "Curaçao",
                fullName: null,
                activeDirectoryName: "Curaçao",
                alpha2: "CW",
                alpha3: "CUW",
                numeric: 531),
            new Country(
                shortName: "Cyprus",
                fullName: "the Republic of Cyprus",
                activeDirectoryName: "Cyprus",
                alpha2: "CY",
                alpha3: "CYP",
                numeric: 196),
            new Country(
                shortName: "Czechia",
                fullName: "the Czech Republic",
                activeDirectoryName: "Czech Republic",
                alpha2: "CZ",
                alpha3: "CZE",
                numeric: 203),
            new Country(
                shortName: "Denmark",
                fullName: "the Kingdom of Denmark",
                activeDirectoryName: "Denmark",
                alpha2: "DK",
                alpha3: "DNK",
                numeric: 208),
            new Country(
                shortName: "Djibouti",
                fullName: "the Republic of Djibouti",
                activeDirectoryName: "Djibouti",
                alpha2: "DJ",
                alpha3: "DJI",
                numeric: 262),
            new Country(
                shortName: "Dominica",
                fullName: "the Commonwealth of Dominica",
                activeDirectoryName: "Dominica",
                alpha2: "DM",
                alpha3: "DMA",
                numeric: 212),
            new Country(
                shortName: "Dominican Republic",
                fullName: "the Dominican Republic",
                activeDirectoryName: "Dominican Republic",
                alpha2: "DO",
                alpha3: "DOM",
                numeric: 214),
            new Country(
                shortName: "Ecuador",
                fullName: "the Republic of Ecuador",
                activeDirectoryName: "Ecuador",
                alpha2: "EC",
                alpha3: "ECU",
                numeric: 218),
            new Country(
                shortName: "Egypt",
                fullName: "the Arab Republic of Egypt",
                activeDirectoryName: "Egypt",
                alpha2: "EG",
                alpha3: "EGY",
                numeric: 818),
            new Country(
                shortName: "El Salvador",
                fullName: "the Republic of El Salvador",
                activeDirectoryName: "El Salvador",
                alpha2: "SV",
                alpha3: "SLV",
                numeric: 222),
            new Country(
                shortName: "Equatorial Guinea",
                fullName: "the Republic of Equatorial Guinea",
                activeDirectoryName: "Equatorial Guinea",
                alpha2: "GQ",
                alpha3: "GNQ",
                numeric: 226),
            new Country(
                shortName: "Eritrea",
                fullName: "the State of Eritrea",
                activeDirectoryName: "Eritrea",
                alpha2: "ER",
                alpha3: "ERI",
                numeric: 232),
            new Country(
                shortName: "Estonia",
                fullName: "the Republic of Estonia",
                activeDirectoryName: "Estonia",
                alpha2: "EE",
                alpha3: "EST",
                numeric: 233),
            new Country(
                shortName: "Ethiopia",
                fullName: "the Federal Democratic Republic of Ethiopia",
                activeDirectoryName: "Ethiopia",
                alpha2: "ET",
                alpha3: "ETH",
                numeric: 231),
            new Country(
                shortName: "Falkland Islands (Malvinas)",
                fullName: null,
                activeDirectoryName: "Falkland Islands (Islas Malvinas)",
                alpha2: "FK",
                alpha3: "FLK",
                numeric: 238),
            new Country(
                shortName: "Faroe Islands",
                fullName: null,
                activeDirectoryName: "Faroe Islands",
                alpha2: "FO",
                alpha3: "FRO",
                numeric: 234),
            new Country(
                shortName: "Fiji",
                fullName: "the Republic of Fiji",
                activeDirectoryName: "Fiji Islands",
                alpha2: "FJ",
                alpha3: "FJI",
                numeric: 242),
            new Country(
                shortName: "Finland",
                fullName: "the Republic of Finland",
                activeDirectoryName: "Finland",
                alpha2: "FI",
                alpha3: "FIN",
                numeric: 246),
            new Country(
                shortName: "France",
                fullName: "the French Republic",
                activeDirectoryName: "France",
                alpha2: "FR",
                alpha3: "FRA",
                numeric: 250),
            new Country(
                shortName: "French Guiana",
                fullName: null,
                activeDirectoryName: "French Guiana",
                alpha2: "GF",
                alpha3: "GUF",
                numeric: 254),
            new Country(
                shortName: "French Polynesia",
                fullName: null,
                activeDirectoryName: "French Polynesia",
                alpha2: "PF",
                alpha3: "PYF",
                numeric: 258),
            new Country(
                shortName: "French Southern Territories",
                fullName: null,
                activeDirectoryName: "French Southern and Antarctic Lands",
                alpha2: "TF",
                alpha3: "ATF",
                numeric: 260),
            new Country(
                shortName: "Gabon",
                fullName: "the Gabonese Republic",
                activeDirectoryName: "Gabon",
                alpha2: "GA",
                alpha3: "GAB",
                numeric: 266),
            new Country(
                shortName: "Gambia",
                fullName: "the Islamic Republic of the Gambia",
                activeDirectoryName: "Gambia, The",
                alpha2: "GM",
                alpha3: "GMB",
                numeric: 270),
            new Country(
                shortName: "Georgia",
                fullName: null,
                activeDirectoryName: "Georgia",
                alpha2: "GE",
                alpha3: "GEO",
                numeric: 268),
            new Country(
                shortName: "Germany",
                fullName: "the Federal Republic of Germany",
                activeDirectoryName: "Germany",
                alpha2: "DE",
                alpha3: "DEU",
                numeric: 276),
            new Country(
                shortName: "Ghana",
                fullName: "the Republic of Ghana",
                activeDirectoryName: "Ghana",
                alpha2: "GH",
                alpha3: "GHA",
                numeric: 288),
            new Country(
                shortName: "Gibraltar",
                fullName: null,
                activeDirectoryName: "Gibraltar",
                alpha2: "GI",
                alpha3: "GIB",
                numeric: 292),
            new Country(
                shortName: "Greece",
                fullName: "the Hellenic Republic",
                activeDirectoryName: "Greece",
                alpha2: "GR",
                alpha3: "GRC",
                numeric: 300),
            new Country(
                shortName: "Greenland",
                fullName: null,
                activeDirectoryName: "Greenland",
                alpha2: "GL",
                alpha3: "GRL",
                numeric: 304),
            new Country(
                shortName: "Grenada",
                fullName: null,
                activeDirectoryName: "Grenada",
                alpha2: "GD",
                alpha3: "GRD",
                numeric: 308),
            new Country(
                shortName: "Guadeloupe",
                fullName: null,
                activeDirectoryName: "Guadeloupe",
                alpha2: "GP",
                alpha3: "GLP",
                numeric: 312),
            new Country(
                shortName: "Guam",
                fullName: null,
                activeDirectoryName: "Guam",
                alpha2: "GU",
                alpha3: "GUM",
                numeric: 316),
            new Country(
                shortName: "Guatemala",
                fullName: "the Republic of Guatemala",
                activeDirectoryName: "Guatemala",
                alpha2: "GT",
                alpha3: "GTM",
                numeric: 320),
            new Country(
                shortName: "Guernsey",
                fullName: null,
                activeDirectoryName: "Guernsey",
                alpha2: "GG",
                alpha3: "GGY",
                numeric: 831),
            new Country(
                shortName: "Guinea",
                fullName: "the Republic of Guinea",
                activeDirectoryName: "Guinea",
                alpha2: "GN",
                alpha3: "GIN",
                numeric: 324),
            new Country(
                shortName: "Guinea-Bissau",
                fullName: "the Republic of Guinea-Bissau",
                activeDirectoryName: "Guinea-Bissau",
                alpha2: "GW",
                alpha3: "GNB",
                numeric: 624),
            new Country(
                shortName: "Guyana",
                fullName: "the Republic of Guyana",
                activeDirectoryName: "Guyana",
                alpha2: "GY",
                alpha3: "GUY",
                numeric: 328),
            new Country(
                shortName: "Haiti",
                fullName: "the Republic of Haiti",
                activeDirectoryName: "Haiti",
                alpha2: "HT",
                alpha3: "HTI",
                numeric: 332),
            new Country(
                shortName: "Heard Island and McDonald Islands",
                fullName: null,
                activeDirectoryName: "Heard Island and McDonald Islands",
                alpha2: "HM",
                alpha3: "HMD",
                numeric: 334),
            new Country(
                shortName: "Holy See",
                fullName: null,
                activeDirectoryName: "Vatican City",
                alpha2: "VA",
                alpha3: "VAT",
                numeric: 336),
            new Country(
                shortName: "Honduras",
                fullName: "the Republic of Honduras",
                activeDirectoryName: "Honduras",
                alpha2: "HN",
                alpha3: "HND",
                numeric: 340),
            new Country(
                shortName: "Hong Kong",
                fullName: "the Hong Kong Special Administrative Region of China",
                activeDirectoryName: "Hong Kong SAR",
                alpha2: "HK",
                alpha3: "HKG",
                numeric: 344),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Howland Island",
                alpha2: null,
                alpha3: null,
                numeric: 581),
            new Country(
                shortName: "Hungary",
                fullName: null,
                activeDirectoryName: "Hungary",
                alpha2: "HU",
                alpha3: "HUN",
                numeric: 348),
            new Country(
                shortName: "Iceland",
                fullName: "the Republic of Iceland",
                activeDirectoryName: "Iceland",
                alpha2: "IS",
                alpha3: "ISL",
                numeric: 352),
            new Country(
                shortName: "India",
                fullName: "the Republic of India",
                activeDirectoryName: "India",
                alpha2: "IN",
                alpha3: "IND",
                numeric: 356),
            new Country(
                shortName: "Indonesia",
                fullName: "the Republic of Indonesia",
                activeDirectoryName: "Indonesia",
                alpha2: "ID",
                alpha3: "IDN",
                numeric: 360),
            new Country(
                shortName: "Iran (Islamic Republic of)",
                fullName: "the Islamic Republic of Iran",
                activeDirectoryName: "Iran",
                alpha2: "IR",
                alpha3: "IRN",
                numeric: 364),
            new Country(
                shortName: "Iraq",
                fullName: "the Republic of Iraq",
                activeDirectoryName: "Iraq",
                alpha2: "IQ",
                alpha3: "IRQ",
                numeric: 368),
            new Country(
                shortName: "Ireland",
                fullName: null,
                activeDirectoryName: "Ireland",
                alpha2: "IE",
                alpha3: "IRL",
                numeric: 372),
            new Country(
                shortName: "Isle of Man",
                fullName: null,
                activeDirectoryName: "Man, Isle of",
                alpha2: "IM",
                alpha3: "IMN",
                numeric: 833),
            new Country(
                shortName: "Israel",
                fullName: "the State of Israel",
                activeDirectoryName: "Israel",
                alpha2: "IL",
                alpha3: "ISR",
                numeric: 376),
            new Country(
                shortName: "Italy",
                fullName: "the Republic of Italy",
                activeDirectoryName: "Italy",
                alpha2: "IT",
                alpha3: "ITA",
                numeric: 380),
            new Country(
                shortName: "Jamaica",
                fullName: null,
                activeDirectoryName: "Jamaica",
                alpha2: "JM",
                alpha3: "JAM",
                numeric: 388),
            new Country(
                shortName: "Japan",
                fullName: null,
                activeDirectoryName: "Japan",
                alpha2: "JP",
                alpha3: "JPN",
                numeric: 392),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Jarvis Island",
                alpha2: null,
                alpha3: null,
                numeric: 581),
            new Country(
                shortName: "Jersey",
                fullName: null,
                activeDirectoryName: "Jersey",
                alpha2: "JE",
                alpha3: "JEY",
                numeric: 832),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Johnston Atoll",
                alpha2: null,
                alpha3: null,
                numeric: 581),
            new Country(
                shortName: "Jordan",
                fullName: "the Hashemite Kingdom of Jordan",
                activeDirectoryName: "Jordan",
                alpha2: "JO",
                alpha3: "JOR",
                numeric: 400),
            new Country(
                shortName: "Kazakhstan",
                fullName: "the Republic of Kazakhstan",
                activeDirectoryName: "Kazakhstan",
                alpha2: "KZ",
                alpha3: "KAZ",
                numeric: 398),
            new Country(
                shortName: "Kenya",
                fullName: "the Republic of Kenya",
                activeDirectoryName: "Kenya",
                alpha2: "KE",
                alpha3: "KEN",
                numeric: 404),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Kingman Reef",
                alpha2: null,
                alpha3: null,
                numeric: 581),
            new Country(
                shortName: "Kiribati",
                fullName: "the Republic of Kiribati",
                activeDirectoryName: "Kiribati",
                alpha2: "KI",
                alpha3: "KIR",
                numeric: 296),
            new Country(
                shortName: "Korea (Democratic People's Republic of)",
                fullName: "the Democratic People's Republic of Korea",
                activeDirectoryName: "North Korea",
                alpha2: "KP",
                alpha3: "PRK",
                numeric: 408),
            new Country(
                shortName: "Korea, Republic of",
                fullName: "the Republic of Korea",
                activeDirectoryName: "Korea",
                alpha2: "KR",
                alpha3: "KOR",
                numeric: 410),
            new Country(
                shortName: "Kuwait",
                fullName: "the State of Kuwait",
                activeDirectoryName: "Kuwait",
                alpha2: "KW",
                alpha3: "KWT",
                numeric: 414),
            new Country(
                shortName: "Kyrgyzstan",
                fullName: "the Kyrgyz Republic",
                activeDirectoryName: "Kyrgyzstan",
                alpha2: "KG",
                alpha3: "KGZ",
                numeric: 417),
            new Country(
                shortName: "Lao People's Democratic Republic",
                fullName: "the Lao People's Democratic Republic",
                activeDirectoryName: "Laos",
                alpha2: "LA",
                alpha3: "LAO",
                numeric: 418),
            new Country(
                shortName: "Latvia",
                fullName: "the Republic of Latvia",
                activeDirectoryName: "Latvia",
                alpha2: "LV",
                alpha3: "LVA",
                numeric: 428),
            new Country(
                shortName: "Lebanon",
                fullName: "the Lebanese Republic",
                activeDirectoryName: "Lebanon",
                alpha2: "LB",
                alpha3: "LBN",
                numeric: 422),
            new Country(
                shortName: "Lesotho",
                fullName: "the Kingdom of Lesotho",
                activeDirectoryName: "Lesotho",
                alpha2: "LS",
                alpha3: "LSO",
                numeric: 426),
            new Country(
                shortName: "Liberia",
                fullName: "the Republic of Liberia",
                activeDirectoryName: "Liberia",
                alpha2: "LR",
                alpha3: "LBR",
                numeric: 430),
            new Country(
                shortName: "Libya",
                fullName: null,
                activeDirectoryName: "Libya",
                alpha2: "LY",
                alpha3: "LBY",
                numeric: 434),
            new Country(
                shortName: "Liechtenstein",
                fullName: "the Principality of Liechtenstein",
                activeDirectoryName: "Liechtenstein",
                alpha2: "LI",
                alpha3: "LIE",
                numeric: 438),
            new Country(
                shortName: "Lithuania",
                fullName: "the Republic of Lithuania",
                activeDirectoryName: "Lithuania",
                alpha2: "LT",
                alpha3: "LTU",
                numeric: 440),
            new Country(
                shortName: "Luxembourg",
                fullName: "the Grand Duchy of Luxembourg",
                activeDirectoryName: "Luxembourg",
                alpha2: "LU",
                alpha3: "LUX",
                numeric: 442),
            new Country(
                shortName: "Macao",
                fullName: "Macao Special Administrative Region of China",
                activeDirectoryName: "Macao SAR",
                alpha2: "MO",
                alpha3: "MAC",
                numeric: 446),
            new Country(
                shortName: "Macedonia, the former Yugoslav Republic of",
                fullName: "the former Yugoslav Republic of Macedonia",
                activeDirectoryName: "Macedonia, Former Yugoslav Republic of",
                alpha2: "MK",
                alpha3: "MKD",
                numeric: 807),
            new Country(
                shortName: "Madagascar",
                fullName: "the Republic of Madagascar",
                activeDirectoryName: "Madagascar",
                alpha2: "MG",
                alpha3: "MDG",
                numeric: 450),
            new Country(
                shortName: "Malawi",
                fullName: "the Republic of Malawi",
                activeDirectoryName: "Malawi",
                alpha2: "MW",
                alpha3: "MWI",
                numeric: 454),
            new Country(
                shortName: "Malaysia",
                fullName: null,
                activeDirectoryName: "Malaysia",
                alpha2: "MY",
                alpha3: "MYS",
                numeric: 458),
            new Country(
                shortName: "Maldives",
                fullName: "the Republic of Maldives",
                activeDirectoryName: "Maldives",
                alpha2: "MV",
                alpha3: "MDV",
                numeric: 462),
            new Country(
                shortName: "Mali",
                fullName: "the Republic of Mali",
                activeDirectoryName: "Mali",
                alpha2: "ML",
                alpha3: "MLI",
                numeric: 466),
            new Country(
                shortName: "Malta",
                fullName: "the Republic of Malta",
                activeDirectoryName: "Malta",
                alpha2: "MT",
                alpha3: "MLT",
                numeric: 470),
            new Country(
                shortName: "Marshall Islands",
                fullName: "the Republic of the Marshall Islands",
                activeDirectoryName: "Marshall Islands",
                alpha2: "MH",
                alpha3: "MHL",
                numeric: 584),
            new Country(
                shortName: "Martinique",
                fullName: null,
                activeDirectoryName: "Martinique",
                alpha2: "MQ",
                alpha3: "MTQ",
                numeric: 474),
            new Country(
                shortName: "Mauritania",
                fullName: "the Islamic Republic of Mauritania",
                activeDirectoryName: "Mauritania",
                alpha2: "MR",
                alpha3: "MRT",
                numeric: 478),
            new Country(
                shortName: "Mauritius",
                fullName: "the Republic of Mauritius",
                activeDirectoryName: "Mauritius",
                alpha2: "MU",
                alpha3: "MUS",
                numeric: 480),
            new Country(
                shortName: "Mayotte",
                fullName: null,
                activeDirectoryName: "Mayotte",
                alpha2: "YT",
                alpha3: "MYT",
                numeric: 175),
            new Country(
                shortName: "Mexico",
                fullName: "the United Mexican States",
                activeDirectoryName: "Mexico",
                alpha2: "MX",
                alpha3: "MEX",
                numeric: 484),
            new Country(
                shortName: "Micronesia (Federated States of)",
                fullName: "the Federated States of Micronesia",
                activeDirectoryName: "Micronesia",
                alpha2: "FM",
                alpha3: "FSM",
                numeric: 583),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Midway Islands",
                alpha2: null,
                alpha3: null,
                numeric: 581),
            new Country(
                shortName: "Moldova, the Republic of",
                fullName: "the Republic of Moldova",
                activeDirectoryName: "Moldova",
                alpha2: "MD",
                alpha3: "MDA",
                numeric: 498),
            new Country(
                shortName: "Monaco",
                fullName: "the Principality of Monaco",
                activeDirectoryName: "Monaco",
                alpha2: "MC",
                alpha3: "MCO",
                numeric: 492),
            new Country(
                shortName: "Mongolia",
                fullName: null,
                activeDirectoryName: "Mongolia",
                alpha2: "MN",
                alpha3: "MNG",
                numeric: 496),
            new Country(
                shortName: "Montenegro",
                fullName: null,
                activeDirectoryName: "Montenegro",
                alpha2: "ME",
                alpha3: "MNE",
                numeric: 499),
            new Country(
                shortName: "Montserrat",
                fullName: null,
                activeDirectoryName: "Montserrat",
                alpha2: "MS",
                alpha3: "MSR",
                numeric: 500),
            new Country(
                shortName: "Morocco",
                fullName: "the Kingdom of Morocco",
                activeDirectoryName: "Morocco",
                alpha2: "MA",
                alpha3: "MAR",
                numeric: 504),
            new Country(
                shortName: "Mozambique",
                fullName: "the Republic of Mozambique",
                activeDirectoryName: "Mozambique",
                alpha2: "MZ",
                alpha3: "MOZ",
                numeric: 508),
            new Country(
                shortName: "Myanmar",
                fullName: "the Republic of the Union of Myanmar",
                activeDirectoryName: "Myanmar",
                alpha2: "MM",
                alpha3: "MMR",
                numeric: 104),
            new Country(
                shortName: "Namibia",
                fullName: "the Republic of Namibia",
                activeDirectoryName: "Namibia",
                alpha2: "NA",
                alpha3: "NAM",
                numeric: 516),
            new Country(
                shortName: "Nauru",
                fullName: "the Republic of Nauru",
                activeDirectoryName: "Nauru",
                alpha2: "NR",
                alpha3: "NRU",
                numeric: 520),
            new Country(
                shortName: "Nepal",
                fullName: "the Federal Democratic Republic of Nepal",
                activeDirectoryName: "Nepal",
                alpha2: "NP",
                alpha3: "NPL",
                numeric: 524),
            new Country(
                shortName: "Netherlands",
                fullName: "the Kingdom of the Netherlands",
                activeDirectoryName: "Netherlands",
                alpha2: "NL",
                alpha3: "NLD",
                numeric: 528),
            new Country(
                shortName: "New Caledonia",
                fullName: null,
                activeDirectoryName: "New Caledonia",
                alpha2: "NC",
                alpha3: "NCL",
                numeric: 540),
            new Country(
                shortName: "New Zealand",
                fullName: null,
                activeDirectoryName: "New Zealand",
                alpha2: "NZ",
                alpha3: "NZL",
                numeric: 554),
            new Country(
                shortName: "Nicaragua",
                fullName: "the Republic of Nicaragua",
                activeDirectoryName: "Nicaragua",
                alpha2: "NI",
                alpha3: "NIC",
                numeric: 558),
            new Country(
                shortName: "Niger",
                fullName: "the Republic of the Niger",
                activeDirectoryName: "Niger",
                alpha2: "NE",
                alpha3: "NER",
                numeric: 562),
            new Country(
                shortName: "Nigeria",
                fullName: "the Federal Republic of Nigeria",
                activeDirectoryName: "Nigeria",
                alpha2: "NG",
                alpha3: "NGA",
                numeric: 566),
            new Country(
                shortName: "Niue",
                fullName: null,
                activeDirectoryName: "Niue",
                alpha2: "NU",
                alpha3: "NIU",
                numeric: 570),
            new Country(
                shortName: "Norfolk Island",
                fullName: null,
                activeDirectoryName: "Norfolk Island",
                alpha2: "NF",
                alpha3: "NFK",
                numeric: 574),
            new Country(
                shortName: "Northern Mariana Islands",
                fullName: "the Commonwealth of the Northern Mariana Islands",
                activeDirectoryName: "Northern Mariana Islands",
                alpha2: "MP",
                alpha3: "MNP",
                numeric: 580),
            new Country(
                shortName: "Norway",
                fullName: "the Kingdom of Norway",
                activeDirectoryName: "Norway",
                alpha2: "NO",
                alpha3: "NOR",
                numeric: 578),
            new Country(
                shortName: "Oman",
                fullName: "the Sultanate of Oman",
                activeDirectoryName: "Oman",
                alpha2: "OM",
                alpha3: "OMN",
                numeric: 512),
            new Country(
                shortName: "Pakistan",
                fullName: "the Islamic Republic of Pakistan",
                activeDirectoryName: "Pakistan",
                alpha2: "PK",
                alpha3: "PAK",
                numeric: 586),
            new Country(
                shortName: "Palau",
                fullName: "the Republic of Palau",
                activeDirectoryName: "Palau",
                alpha2: "PW",
                alpha3: "PLW",
                numeric: 585),
            new Country(
                shortName: "Palestine, State of",
                fullName: "the State of Palestine",
                activeDirectoryName: "Palestinian Authority",
                alpha2: "PS",
                alpha3: "PSE",
                numeric: 275),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Palmyra Atoll",
                alpha2: null,
                alpha3: null,
                numeric: 581),
            new Country(
                shortName: "Panama",
                fullName: "the Republic of Panama",
                activeDirectoryName: "Panama",
                alpha2: "PA",
                alpha3: "PAN",
                numeric: 591),
            new Country(
                shortName: "Papua New Guinea",
                fullName: "the Independent State of Papua New Guinea",
                activeDirectoryName: "Papua New Guinea",
                alpha2: "PG",
                alpha3: "PNG",
                numeric: 598),
            new Country(
                shortName: "Paraguay",
                fullName: "the Republic of Paraguay",
                activeDirectoryName: "Paraguay",
                alpha2: "PY",
                alpha3: "PRY",
                numeric: 600),
            new Country(
                shortName: "Peru",
                fullName: "the Republic of Peru",
                activeDirectoryName: "Peru",
                alpha2: "PE",
                alpha3: "PER",
                numeric: 604),
            new Country(
                shortName: "Philippines",
                fullName: "the Republic of the Philippines",
                activeDirectoryName: "Philippines",
                alpha2: "PH",
                alpha3: "PHL",
                numeric: 608),
            new Country(
                shortName: "Pitcairn",
                fullName: null,
                activeDirectoryName: "Pitcairn Islands",
                alpha2: "PN",
                alpha3: "PCN",
                numeric: 612),
            new Country(
                shortName: "Poland",
                fullName: "the Republic of Poland",
                activeDirectoryName: "Poland",
                alpha2: "PL",
                alpha3: "POL",
                numeric: 616),
            new Country(
                shortName: "Portugal",
                fullName: "the Portuguese Republic",
                activeDirectoryName: "Portugal",
                alpha2: "PT",
                alpha3: "PRT",
                numeric: 620),
            new Country(
                shortName: "Puerto Rico",
                fullName: null,
                activeDirectoryName: "Puerto Rico",
                alpha2: "PR",
                alpha3: "PRI",
                numeric: 630),
            new Country(
                shortName: "Qatar",
                fullName: null,
                activeDirectoryName: "Qatar",
                alpha2: "QA",
                alpha3: "QAT",
                numeric: 634),
            new Country(
                shortName: "Réunion",
                fullName: null,
                activeDirectoryName: "Réunion",
                alpha2: "RE",
                alpha3: "REU",
                numeric: 638),
            new Country(
                shortName: "Romania",
                fullName: null,
                activeDirectoryName: "Romania",
                alpha2: "RO",
                alpha3: "ROU",
                numeric: 642),
            new Country(
                shortName: "Russian Federation",
                fullName: "the Russian Federation",
                activeDirectoryName: "Russia",
                alpha2: "RU",
                alpha3: "RUS",
                numeric: 643),
            new Country(
                shortName: "Rwanda",
                fullName: "the Republic of Rwanda",
                activeDirectoryName: "Rwanda",
                alpha2: "RW",
                alpha3: "RWA",
                numeric: 646),
            new Country(
                shortName: "Saint Barthélemy",
                fullName: null,
                activeDirectoryName: "Saint Barthélemy",
                alpha2: "BL",
                alpha3: "BLM",
                numeric: 652),
            new Country(
                shortName: "Saint Helena, Ascension and Tristan da Cunha",
                fullName: null,
                activeDirectoryName: "Saint Helena, Ascension and Tristan da Cunha",
                alpha2: "SH",
                alpha3: "SHN",
                numeric: 654),
            new Country(
                shortName: "Saint Kitts and Nevis",
                fullName: null,
                activeDirectoryName: "St. Kitts and Nevis",
                alpha2: "KN",
                alpha3: "KNA",
                numeric: 659),
            new Country(
                shortName: "Saint Lucia",
                fullName: null,
                activeDirectoryName: "St. Lucia",
                alpha2: "LC",
                alpha3: "LCA",
                numeric: 662),
            new Country(
                shortName: "Saint Martin (French part)",
                fullName: null,
                activeDirectoryName: "Saint Martin (French part)",
                alpha2: "MF",
                alpha3: "MAF",
                numeric: 663),
            new Country(
                shortName: "Saint Pierre and Miquelon",
                fullName: null,
                activeDirectoryName: "St. Pierre and Miquelon",
                alpha2: "PM",
                alpha3: "SPM",
                numeric: 666),
            new Country(
                shortName: "Saint Vincent and the Grenadines",
                fullName: null,
                activeDirectoryName: "St. Vincent and the Grenadines",
                alpha2: "VC",
                alpha3: "VCT",
                numeric: 670),
            new Country(
                shortName: "Samoa",
                fullName: "the Independent State of Samoa",
                activeDirectoryName: "Samoa",
                alpha2: "WS",
                alpha3: "WSM",
                numeric: 882),
            new Country(
                shortName: "San Marino",
                fullName: "the Republic of San Marino",
                activeDirectoryName: "San Marino",
                alpha2: "SM",
                alpha3: "SMR",
                numeric: 674),
            new Country(
                shortName: "Sao Tome and Principe",
                fullName: "the Democratic Republic of Sao Tome and Principe",
                activeDirectoryName: "São Tomé and Príncipe",
                alpha2: "ST",
                alpha3: "STP",
                numeric: 678),
            new Country(
                shortName: "Saudi Arabia",
                fullName: "the Kingdom of Saudi Arabia",
                activeDirectoryName: "Saudi Arabia",
                alpha2: "SA",
                alpha3: "SAU",
                numeric: 682),
            new Country(
                shortName: "Senegal",
                fullName: "the Republic of Senegal",
                activeDirectoryName: "Senegal",
                alpha2: "SN",
                alpha3: "SEN",
                numeric: 686),
            new Country(
                shortName: "Serbia",
                fullName: "the Republic of Serbia",
                activeDirectoryName: "Serbia",
                alpha2: "RS",
                alpha3: "SRB",
                numeric: 688),
             new Country(
                 shortName: null,
                 fullName: null,
                 activeDirectoryName: "Serbia and Montenegro (Former)",
                 alpha2: "CS",
                 alpha3: "SCG",
                 numeric: 891),
             new Country(
                 shortName: "Seychelles",
                 fullName: "the Republic of Seychelles",
                 activeDirectoryName: "Seychelles",
                 alpha2: "SC",
                 alpha3: "SYC",
                 numeric: 690),
            new Country(
                shortName: "Sierra Leone",
                fullName: "the Republic of Sierra Leone",
                activeDirectoryName: "Sierra Leone",
                alpha2: "SL",
                alpha3: "SLE",
                numeric: 694),
            new Country(
                shortName: "Singapore",
                fullName: "the Republic of Singapore",
                activeDirectoryName: "Singapore",
                alpha2: "SG",
                alpha3: "SGP",
                numeric: 702),
            new Country(
                shortName: "Sint Maarten (Dutch part)",
                fullName: null,
                activeDirectoryName: "Sint Maarten (Dutch part)",
                alpha2: "SX",
                alpha3: "SXM",
                numeric: 534),
            new Country(
                shortName: "Slovakia",
                fullName: "the Slovak Republic",
                activeDirectoryName: "Slovakia",
                alpha2: "SK",
                alpha3: "SVK",
                numeric: 703),
            new Country(
                shortName: "Slovenia",
                fullName: "the Republic of Slovenia",
                activeDirectoryName: "Slovenia",
                alpha2: "SI",
                alpha3: "SVN",
                numeric: 705),
            new Country(
                shortName: "Solomon Islands",
                fullName: null,
                activeDirectoryName: "Solomon Islands",
                alpha2: "SB",
                alpha3: "SLB",
                numeric: 90),
            new Country(
                shortName: "Somalia",
                fullName: "the Federal Republic of Somalia",
                activeDirectoryName: "Somalia",
                alpha2: "SO",
                alpha3: "SOM",
                numeric: 706),
            new Country(
                shortName: "South Africa",
                fullName: "the Republic of South Africa",
                activeDirectoryName: "South Africa",
                alpha2: "ZA",
                alpha3: "ZAF",
                numeric: 710),
            new Country(
                shortName: "South Georgia and the South Sandwich Islands",
                fullName: null,
                activeDirectoryName: "South Georgia and the South Sandwich Islands",
                alpha2: "GS",
                alpha3: "SGS",
                numeric: 239),
            new Country(
                shortName: "South Sudan",
                fullName: "the Republic of South Sudan",
                activeDirectoryName: "South Sudan",
                alpha2: "SS",
                alpha3: "SSD",
                numeric: 728),
            new Country(
                shortName: "Spain",
                fullName: "the Kingdom of Spain",
                activeDirectoryName: "Spain",
                alpha2: "ES",
                alpha3: "ESP",
                numeric: 724),
            new Country(
                shortName: "Sri Lanka",
                fullName: "the Democratic Socialist Republic of Sri Lanka",
                activeDirectoryName: "Sri Lanka",
                alpha2: "LK",
                alpha3: "LKA",
                numeric: 144),
            new Country(
                shortName: "Sudan",
                fullName: "the Republic of the Sudan",
                activeDirectoryName: "Sudan",
                alpha2: "SD",
                alpha3: "SDN",
                numeric: 729),
            new Country(
                shortName: "Suriname",
                fullName: "the Republic of Suriname",
                activeDirectoryName: "Suriname",
                alpha2: "SR",
                alpha3: "SUR",
                numeric: 740),
            new Country(
                shortName: "Svalbard and Jan Mayen",
                fullName: null,
                activeDirectoryName: "Svalbard",
                alpha2: "SJ",
                alpha3: "SJM",
                numeric: 744),
            new Country(
                shortName: "Swaziland",
                fullName: "the Kingdom of Swaziland",
                activeDirectoryName: "Swaziland",
                alpha2: "SZ",
                alpha3: "SWZ",
                numeric: 748),
            new Country(
                shortName: "Sweden",
                fullName: "the Kingdom of Sweden",
                activeDirectoryName: "Sweden",
                alpha2: "SE",
                alpha3: "SWE",
                numeric: 752),
            new Country(
                shortName: "Switzerland",
                fullName: "the Swiss Confederation",
                activeDirectoryName: "Switzerland",
                alpha2: "CH",
                alpha3: "CHE",
                numeric: 756),
            new Country(
                shortName: "Syrian Arab Republic",
                fullName: "the Syrian Arab Republic",
                activeDirectoryName: "Syria",
                alpha2: "SY",
                alpha3: "SYR",
                numeric: 760),
            new Country(
                shortName: "Taiwan, Province of China",
                fullName: null,
                activeDirectoryName: "Taiwan",
                alpha2: "TW",
                alpha3: "TWN",
                numeric: 158),
            new Country(
                shortName: "Tajikistan",
                fullName: "the Republic of Tajikistan",
                activeDirectoryName: "Tajikistan",
                alpha2: "TJ",
                alpha3: "TJK",
                numeric: 762),
            new Country(
                shortName: "Tanzania, United Republic of",
                fullName: "the United Republic of Tanzania",
                activeDirectoryName: "Tanzania",
                alpha2: "TZ",
                alpha3: "TZA",
                numeric: 834),
            new Country(
                shortName: "Thailand",
                fullName: "the Kingdom of Thailand",
                activeDirectoryName: "Thailand",
                alpha2: "TH",
                alpha3: "THA",
                numeric: 764),
            new Country(
                shortName: "Timor-Leste",
                fullName: "the Democratic Republic of Timor-Leste",
                activeDirectoryName: "Democratic Republic of Timor-Leste",
                alpha2: "TL",
                alpha3: "TLS",
                numeric: 626),
            new Country(
                shortName: "Togo",
                fullName: "the Togolese Republic",
                activeDirectoryName: "Togo",
                alpha2: "TG",
                alpha3: "TGO",
                numeric: 768),
            new Country(
                shortName: "Tokelau",
                fullName: null,
                activeDirectoryName: "Tokelau",
                alpha2: "TK",
                alpha3: "TKL",
                numeric: 772),
            new Country(
                shortName: "Tonga",
                fullName: "the Kingdom of Tonga",
                activeDirectoryName: "Tonga",
                alpha2: "TO",
                alpha3: "TON",
                numeric: 776),
            new Country(
                shortName: "Trinidad and Tobago",
                fullName: "the Republic of Trinidad and Tobago",
                activeDirectoryName: "Trinidad and Tobago",
                alpha2: "TT",
                alpha3: "TTO",
                numeric: 780),
            new Country(
                shortName: "Tunisia",
                fullName: "the Republic of Tunisia",
                activeDirectoryName: "Tunisia",
                alpha2: "TN",
                alpha3: "TUN",
                numeric: 788),
            new Country(
                shortName: "Turkey",
                fullName: "the Republic of Turkey",
                activeDirectoryName: "Turkey",
                alpha2: "TR",
                alpha3: "TUR",
                numeric: 792),
            new Country(
                shortName: "Turkmenistan",
                fullName: null,
                activeDirectoryName: "Turkmenistan",
                alpha2: "TM",
                alpha3: "TKM",
                numeric: 795),
            new Country(
                shortName: "Turks and Caicos Islands",
                fullName: null,
                activeDirectoryName: "Turks and Caicos Islands",
                alpha2: "TC",
                alpha3: "TCA",
                numeric: 796),
            new Country(
                shortName: "Tuvalu",
                fullName: null,
                activeDirectoryName: "Tuvalu",
                alpha2: "TV",
                alpha3: "TUV",
                numeric: 798),
            new Country(
                shortName: "Uganda",
                fullName: "the Republic of Uganda",
                activeDirectoryName: "Uganda",
                alpha2: "UG",
                alpha3: "UGA",
                numeric: 800),
            new Country(
                shortName: "Ukraine",
                fullName: null,
                activeDirectoryName: "Ukraine",
                alpha2: "UA",
                alpha3: "UKR",
                numeric: 804),
            new Country(
                shortName: "United Arab Emirates",
                fullName: "the United Arab Emirates",
                activeDirectoryName: "United Arab Emirates",
                alpha2: "AE",
                alpha3: "ARE",
                numeric: 784),
            new Country(
                shortName: "United Kingdom of Great Britain and Northern Ireland",
                fullName: "the United Kingdom of Great Britain and Northern Ireland",
                activeDirectoryName: "United Kingdom",
                alpha2: "GB",
                alpha3: "GBR",
                numeric: 826),
            new Country(
                shortName: "United States Minor Outlying Islands",
                fullName: null,
                activeDirectoryName: "U.S. Minor Outlying Islands",
                alpha2: "UM",
                alpha3: "UMI",
                numeric: 581),
            new Country(
                shortName: "United States of America",
                fullName: "the United States of America",
                activeDirectoryName: "United States",
                alpha2: "US",
                alpha3: "USA",
                numeric: 840),
            new Country(
                shortName: "Uruguay",
                fullName: "the Eastern Republic of Uruguay",
                activeDirectoryName: "Uruguay",
                alpha2: "UY",
                alpha3: "URY",
                numeric: 858),
            new Country(
                shortName: "Uzbekistan",
                fullName: "the Republic of Uzbekistan",
                activeDirectoryName: "Uzbekistan",
                alpha2: "UZ",
                alpha3: "UZB",
                numeric: 860),
            new Country(
                shortName: "Vanuatu",
                fullName: "the Republic of Vanuatu",
                activeDirectoryName: "Vanuatu",
                alpha2: "VU",
                alpha3: "VUT",
                numeric: 548),
            new Country(
                shortName: "Venezuela (Bolivarian Republic of)",
                fullName: "the Bolivarian Republic of Venezuela",
                activeDirectoryName: "Bolivarian Republic of Venezuela",
                alpha2: "VE",
                alpha3: "VEN",
                numeric: 862),
            new Country(
                shortName: "Viet Nam",
                fullName: "the Socialist Republic of Viet Nam",
                activeDirectoryName: "Vietnam",
                alpha2: "VN",
                alpha3: "VNM",
                numeric: 704),
            new Country(
                shortName: "Virgin Islands (British)",
                fullName: "British Virgin Islands (the)",
                activeDirectoryName: "Virgin Islands, British",
                alpha2: "VG",
                alpha3: "VGB",
                numeric: 92),
            new Country(
                shortName: "Virgin Islands (U.S.)",
                fullName: "the Virgin Islands of the United States",
                activeDirectoryName: "Virgin Islands",
                alpha2: "VI",
                alpha3: "VIR",
                numeric: 850),
            new Country(
                shortName: null,
                fullName: null,
                activeDirectoryName: "Wake Island",
                alpha2: null,
                alpha3: null,
                numeric: 581),
            new Country(
                shortName: "Wallis and Futuna",
                fullName: "Wallis and Futuna Islands",
                activeDirectoryName: "Wallis and Futuna",
                alpha2: "WF",
                alpha3: "WLF",
                numeric: 876),
            new Country(
                shortName: "Western Sahara",
                fullName: null,
                activeDirectoryName: null,
                alpha2: "EH",
                alpha3: "ESH",
                numeric: 732),
            new Country(
                shortName: "Yemen",
                fullName: "the Republic of Yemen",
                activeDirectoryName: "Yemen",
                alpha2: "YE",
                alpha3: "YEM",
                numeric: 887),
            new Country(
                shortName: "Zambia",
                fullName: "the Republic of Zambia",
                activeDirectoryName: "Zambia",
                alpha2: "ZM",
                alpha3: "ZMB",
                numeric: 894),
            new Country(
                shortName: "Zimbabwe",
                fullName: "the Republic of Zimbabwe",
                activeDirectoryName: "Zimbabwe",
                alpha2: "ZW",
                alpha3: "ZWE",
                numeric: 716)
        }.AsReadOnly();
    }
}
